apiVersion: ENC[AES256_GCM,data:LoA=,iv:/kYuvgJnTa5Lo1jcmEglPlcMYX8oeWYjLuuL295ytxk=,tag:mVql3IpVhdAZP3Aqp04AfQ==,type:str]
kind: ENC[AES256_GCM,data:gVurEGJa,iv:GrYmle2wnEjQn9KaaQ4E0t5uhmQZCvhyxHx+GFEjX1U=,tag:fZ+EWJ3dGWiJWZr+/197nQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yYrZEkkU7T11YC3Hu+BxGLD0qKF6,iv:20Gd/qWHcNxwwaY/XdNEs2IF7QEzYZorhRjlDx7YReU=,tag:UOJrHvKD8SPiaWMNxBwFmA==,type:str]
    namespace: ENC[AES256_GCM,data:yNvgXpCRMFCJvA==,iv:8nz/2JOeCIOGmWHs0QdVMT9TYUrx1FeGp/db9mUQrmk=,tag:zjQ6vSqfAdee7iXYu4gsjQ==,type:str]
type: ENC[AES256_GCM,data:82uun/9w,iv:cIhO8fc8PJqDd8GJtWKD4weAT/CmRWjCzGmy44PdzfE=,tag:6ddWvCIbJ5Gqb4jLpaKnNw==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4yeQx4samjNB9Ss6exUiLBmqhBP2N5noLA==,iv:FbNsu981PuatXuw6mYUrVWdMytDL0xheWWqMppWxAEI=,tag:RmFh98ElRzC39afJKjgRQg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pZDC3CfkrW8sXPRuDeefVvumxknd6JgtOM0Lcg7F9A==,iv:xIzj642jMBMa7PbVOhDM2XaQC8DQo+ldHTBbJqIxqqg=,tag:4d62Xpj/yopGClN7qYNFvA==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ECq01IPGTJ456w3C8P5cHe71vpbBnd80N9PvICYXFrhPVcW/Q4drjJ0WIuNUo/HN/vbnyrqwtgVMSTwNEiM64FZUFeT386O2,iv:LSCxbw6jh62Knhz4cyLWBB0aQSeewdJpjko6pUp7vqY=,tag:+u/N55JBdpSGMZnagiXaGA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:qgXWOeZSkTDOE0sro9dSDcoubw/6mu0m+EiKOtmJEJik+GwNQEjEHOcDeag=,iv:bBow3hNiqb3rNRj5I8DUObSe8dCqan4nTf4Lq+VzpI0=,tag:Qp+17FiLVCeLSlU6ro0wQQ==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TW5udGEwSUk3c0NPWCtG
            YzFncU1PQjk4MCtkczlXc3Rsaml0VSt3UkNvCjIrdWR2UmNEQndoaFV2bWNmNVh4
            bWJZSDBOaVpJVExrenJBbmxYNmRDZ2sKLS0tICtBU0llSDZJN0lKSkgwdVhhZ052
            WVhCV0NHVUJsS2oraEZ1NVl4QU82TU0K2AipcsyE+W4uRTan+m6FXV5I+b0Azave
            0h9cwdxT6PweO8XKlPyetnXWPCD3/LLhPZThA4pKqJjhP3X4WAhbMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T00:58:39Z"
    mac: ENC[AES256_GCM,data:HWwH0xbNDG/Dk/qQUJCrnWKe8TLA3kV0BfOTMWGL/sXcoC5ZM5cfoSQYlcJ0lv51BAGeQTCkPpeds04Cs1tSURKFSxbpwVq//dKuuOOZRotHL3YkufzikSBzj1Yh+90bfuITPcmvAvy9wdMKYv6Yqw76GLqkSk9vQzUjkQMOOgU=,iv:GIjxVkbc5WQgAsEXDWNf7HMAs9PLzpo1c7ln3Sct+5I=,tag:kYC8Qxz21vOt3onkdPcIsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
