apiVersion: ENC[AES256_GCM,data:3iY=,iv:Ah0WR8ujmHZ/ZC33nz2vgxPX2i9IzZG/XpxtpoQ0LHE=,tag:kia2+4TcKLr2FZHbO5JCyQ==,type:str]
kind: ENC[AES256_GCM,data:UoR8ykC2,iv:sxF5L05zGpxqUqZE+uGGcQKU+xx4QEDozr9EaEL/Lt0=,tag:eMyZZJtN+3F7xyVWVc6MnQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:x6DEodFU5vakkmaPMNTeJhkjHA==,iv:Hd5MhyqoZ1uXFltL8sX/V2e+OvzEeEY/orXyS0jynLM=,tag:mKjFbAOPjpp6JGl/Ed0T4g==,type:str]
    namespace: ENC[AES256_GCM,data:hgQBP8ValJBUuw==,iv:kvPafEdsvPbXSTpN8XAJQHJUcBimCS+NRyMELv+0AwI=,tag:V9yP+qk+fCCXeyfvx7RNtA==,type:str]
type: ENC[AES256_GCM,data:tNym6Wjh,iv:jvhwcO9A/D016k7tjzPsWFJcukdM0ZpaUGz07T0t5GU=,tag:wp/E0gHA+wTuRRlnJ9S6og==,type:str]
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:zoEYIeyn6gdsmP7IKFwtcrkzT6KgKiKJVf5UBU1THn+llxwAH9EseA0jPnDxu3VdguVucKt8N3ehyKyddIZDbA==,iv:lXBY0gP3UYop3UwCZz9BSN/qzOfYHLzZYpWOc2AcAdo=,tag:wwD9GEZ6CwsDKCf8VxUBqg==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArT25oWUZEUzd0REFETEpl
            bmVGSXdUWmxkYXhiN2ZheVE5bnJWNE41SndnCldIRldQTnlsbFIxaWJXR3lXeGl5
            K2pia1NSVGJ5SEROVjdjVm5CWFMwVlkKLS0tIFU5UERScGRNOTZzYUlhWXV5c0NZ
            SmdabnpSOE5TUklEQVBuWmZ1SVlWYTAKGBc8V1e4uwsTpi9JTbuDcbkHZ9jQdWqS
            THVgf9YN0r3w5EAjQnN9aZGDLm8IQht/s+dH34HOrgM1ZMxBKZCt4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T23:43:49Z"
    mac: ENC[AES256_GCM,data:RpDbUbg1O+rsk+H18AKtuZyd/BgOmH1Tdg3zmiK1lhjkseaGIvUYqz0jOa/7wNI60zqMMDaAvRPBTz6a1becxungT7+LnlnkYs8/yyITQd6xcDYu6YpfLvLv41gV/uUmCeuGPA+PQpNx9CVPct7iGNvyCiVEIX0I15+VzVIz8lg=,iv:A1Vr258e2Y7bnq6S8t3N8fpVlUmKQxtjcK1lLvlVstY=,tag:mcJziusCwnMBOy5D5Cw+Xw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
