apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: monitoring-internal
  namespace: monitoring
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
