apiVersion: ENC[AES256_GCM,data:/to=,iv:HNqZ0CEiwsfnFkwN7hBh5engNnyqxfi5p1xtOqbjoFU=,tag:xdv3887Lr7Zo2xmw/OLQwA==,type:str]
kind: ENC[AES256_GCM,data:F8hLnKXB,iv:MLZvQ/mZjejqDBGITRnLtBFjkeCHRm7gXJdeTCI+92U=,tag:oQ614H0QHdVT1Vj8sdid1g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GTrGmQS54nmATZXvxo1BuHqbX7cm,iv:Id5GmXgxAwBFBf4pawvpWmE6vyeTPCGq6fD5L2JjbPI=,tag:3f+2N6D8LnezxDZZb8VnkA==,type:str]
    namespace: ENC[AES256_GCM,data:7ip5Rigt2JzSBA==,iv:eC8ohqP+z6WUFak81EbEF/b0hDThrH6uDyz4rnLYs8Y=,tag:yccEPEJFdjGmGZJK2tlejQ==,type:str]
type: ENC[AES256_GCM,data:minSeHDz,iv:3KflLAu3SY3hFwbLmjsuznGIn0fojN4PxGQP1PsbID8=,tag:osXIsKFUAe2UJ0wPScV6Tg==,type:str]
stringData:
    bot-token: ENC[AES256_GCM,data:2iUqt6Ji5zLZDoKOlNlhwMPQkQeJOFJQT5Nl3vyMVh5YPdCwQ2GKSQmvxzImeQ==,iv:2kKaX1Srz64w++1NBU7YY/sXkdU38zE4BOoru8dJMkk=,tag:oAhgLgPyqcBjlbuV2yOKiw==,type:str]
    chat-id: ENC[AES256_GCM,data:EKCWut2gLDiR,iv:987D9PbLCQFgIYMrJVYcokzKJCVwcqda9IT/fLGQxYo=,tag:Oacy6Ny+E8URoVL26Npo4Q==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRGxkR2ZXZHV4dUNiQ05y
            MFBkRWZNdklPeEc5c1ZCOWFiS3dSSU53Q2wwClNta2dLUElQbkphNEhHbmkyalRQ
            Wmw5eSt6YmVMV2xDcFNCbFhiMGpRY0kKLS0tIGdXcUp0b09Mb1lCdmxjSlZLQmhY
            OXZycGdMSzZRU3hVZ1NNQXpQTFdUVWsKcnniBNCS8MMWdk3XC3gRMCdgfn0H6PPa
            nxMqwEAdyg6lluFIV8M6QZTEQwujFhPJbDhqZA/f35Kbdo8ljoh4Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T10:49:08Z"
    mac: ENC[AES256_GCM,data:9C6LdSnP+7HYi6GOEmv3Uu0a1cVB6VefqebM7w6fxN5kP8kXCJxWlfguundgJi6++R63DBCxpWwzXpmfE+muBXJOn4ALU4utpc/5n3reGUBIvfdokDYX7OlllunzXLili2lIiIotCgGcX72oQZQPqrCW42yuaFpe9VAQs4pmHvs=,iv:g7Xhvm88cESsxyA0os5EhqqK6Q2MU29QKkjRjtt2vU8=,tag:ZzXkd35pDDkW+natZAdtaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
