apiVersion: ENC[AES256_GCM,data:Sa4=,iv:co3z1qUqhHcK1MtACTnPnDrYZGCA/gEnbJAWuaGgPbY=,tag:UqvtVFwTg7zAnO37c/RRYQ==,type:str]
kind: ENC[AES256_GCM,data:ZyIIADNO,iv:Z0egjpeGy6QyBEIzJbqg43WTwoc3EYVlHYdn+oMRDBY=,tag:xAUTSy5ruN2PmqygCGz6ZA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LUNvs+BzNq3OpzfysJjB28ETJl2a,iv:HApFj1ZmM7u/13+h/Kdg3CE1He2PKBb+pGj5fj/KBWE=,tag:ZuG3xGujsnr++U/XeyEFHA==,type:str]
    namespace: ENC[AES256_GCM,data:okl4SFJnwbwizQ==,iv:vDk0rmCEOgjzERiQfqWK07t+1qvaUg+0jMlpyNFiBO8=,tag:dit9BzCO4S6yt+d9jLh0Xw==,type:str]
type: ENC[AES256_GCM,data:CqJqX23u,iv:4LFuFuamYex/Mty0vZZl103yJd3Z2dg+cYwgi///ZAE=,tag:pDxqNABV0279yuHTDFfxlQ==,type:str]
stringData:
    bot-token: ENC[AES256_GCM,data:UIIm98oEp6WntLAkB9k373heVzC9IrhxuaEuPb8nh3R5XbT/Fx8Fi3VXO6hlqQ==,iv:oAEqjrETv2r2hdNBM9/4yFXFzPPyTiyYgJRJYnhvH94=,tag:VWxlQAoNbmGs3esOhCSrFA==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cHZWYTQvenQ2M0M3RG53
            SmZZdGxXand3R1FPaDV3TkVYOXFIenladzJFCk9PSW1DMkRuUkI2M0pKTm12ZHZu
            WEdVYzJaL0MwdW1jTG5KcWs3RTdlN0UKLS0tIEZaZUZzR3F6bDFwWG81Vmd3Q05n
            SitDZWNZMEVDaTdLVTBNa2l0Vmg3TW8K4AhIF4NnIKiMUiX2oKMOn132Jf65NXtN
            vu13ZFVau67lma32h9CW9zuI72XLreSSosueV0Bc2q4+Zhq/H5aeQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T10:35:14Z"
    mac: ENC[AES256_GCM,data:hWHorhO5pDNos/EwabYburZWvqQCxpZBrtA6KtsNhkj07POTA3vZmlNvMVyt0tOhW995gu8tHQXsbO6Q/OExsRvgWtPxu2mvFjNf7pi6GlbRwvHgmqrQ4qkd6dKsWKa0geSe6QI1vbV0oIcGI1bzaKmlM2M5ySeOwhOQfrZOkc8=,iv:XLvHRh21zj2x0eEXfqtqO79nWhd7OYPQMZOzkdhWu1s=,tag:ZnkalhKQGJqjcuMPTt34rw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
