apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homelab-postgres
  namespace: postgres
spec:
  instances: 2
  storage:
    size: 10Gi
    storageClass: longhorn-single
  postgresql:
    parameters:
      max_connections: "200"
  bootstrap:
    recovery:
      source: homelab-postgres-source
  backup:
    barmanObjectStore:
      destinationPath: s3://pmd-homelab-backups/postgres
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      serverName: homelab-postgres-v5
      s3Credentials:
        accessKeyId:
          name: pg-backup-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: pg-backup-secret
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "7d"
  externalClusters:
    - name: homelab-postgres-source
      barmanObjectStore:
        destinationPath: s3://pmd-homelab-backups/postgres
        endpointURL: https://s3.eu-central-003.backblazeb2.com
        serverName: homelab-postgres
        s3Credentials:
          accessKeyId:
            name: pg-backup-secret
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: pg-backup-secret
            key: ACCESS_SECRET_KEY
        wal:
          compression: gzip
        data:
          compression: gzip
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
