apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cluster.yaml
  - networkpolicy.yaml
  - pg-password.enc.yaml
  - pg-backup-secret.enc.yaml
  - scheduled-backup.yaml
  - cnpg-rules.yaml
  - pdb.yaml
