apiVersion: ENC[AES256_GCM,data:u0A=,iv:azpLXHilKyAwTdNqknI7pvYwuo0iIleNXdropLgVz00=,tag:yiZQH3PD5wNiQVvO7go0Iw==,type:str]
kind: ENC[AES256_GCM,data:MyHZBOQC,iv:53Micf7mgaaidFpGWa93AaQVbRO4HFIVzEpCE/Zubh0=,tag:LF5INSJNOStfBzm1Alc3KQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WFWbnPBgc/fDjawAAZ0Cdg==,iv:OGWzJ2vrF19oRHJwidz6cQE/TTcw2XHYa1IzsWSKlXo=,tag:uahaqX3N2/Qf5RcRf2512Q==,type:str]
    namespace: ENC[AES256_GCM,data:A/rAj6JolZw=,iv:VSIen/NfNINg4JP6E9Dq7CQvJP7DWjYHSa9TKVEnkpQ=,tag:l1FZsi6bWoBfYDBcOb4DiQ==,type:str]
type: ENC[AES256_GCM,data:fc/9hf3b,iv:Ro6CTN/QHoY8vjXafPrifb+YtYBTbY+ZLTNJxaLQX58=,tag:NQroOEHmWjaRdS79WG66dA==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:Yn0ELSMi5g34tQvgUJokE11kTH04UNMxCQ==,iv:An99EWrir1ywRWpWmb1jlEw1lyhH/TqtD5b+D/OndaY=,tag:eo3gd+EZJJNLxMBbw2mFFA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:3FRjqOqAsxxuEqJwa5FUKXzbebRlyYFUjj3N82Bdkg==,iv:4FQ6n+X+MmNN4s6/Szx9mmC4Qu+MMGKFdx3DZJD1wys=,tag:EMZ1bX74MkU+KG/KOb+zbA==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYyswNjdRUW8vTEd4UDg4
            dHlxRWdFOGZ6SWpycFptUmxDMUVlS2xGYkhrCkpjZnZpK3JScGVwcmNUTnpJN2tR
            NmZTSDBSbGJ2UVJNMWcrRmVUMXorUXcKLS0tIDMrY3hraUhFOGI1R1lWR3lTZm1D
            Sk9ONmNSNFFxV2g2OVF4OWk5WnU1TDAKqygHZPRx/3i1lajUYRwxejp1eelI79gJ
            E59Vhhflmz8pNbGl4NClF3/qDMf8ChTQvm7f8m7JL9SrO61M0DmuIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T01:03:19Z"
    mac: ENC[AES256_GCM,data:GbyfUq6YLf62vOlGHOyYIYDj39v7eFoDFIXMlHsv0tFnSc2UkgLhxToSuhOtTCZrYTS96CYGxO4jDztzCP6n0u1mQF7g3YvlwuCDc4PmfwhABE8g9/nW1bjS3JoHgegustBSTXdqoESZQqu+yC5v6x3VDVodxkRxiB3b817LoMU=,iv:feRH4Pc+JhaL8avRoDEFWFSRfvX+izH5tr8lxWx+Z0g=,tag:0VKbontXcUZCpLPBtHSf1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
