apiVersion: ENC[AES256_GCM,data:yQo=,iv:K0ZrvvBGfMc5bRToILeb882D6snTbf7w8rZekcU+vOE=,tag:ubvZjzCyFWvwTE94cDfIdg==,type:str]
kind: ENC[AES256_GCM,data:2YpLG7LX,iv:S2GJ4nTVRkKUKV23mAiwe08WetcbliLaMNMB5ZrFqhI=,tag:MfyeDbNru4sqYu4FFjs59A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rvQysfZr202iAqI=,iv:33AeBOyvOFKapMZIas8Ioa3ir5mDaZ9eAIjhZj61nFU=,tag:AeP1JQHncyYjQhGLt+e+bA==,type:str]
    namespace: ENC[AES256_GCM,data:XlAI0x4nrjc=,iv:eJckWSxBuhjo70RtlJSZl9RXVvgVMSkTCeqM9qFbbAQ=,tag:WrJZNPyql90EFrwrWBcTog==,type:str]
type: ENC[AES256_GCM,data:001w/24h,iv:vyiWKUPGGb1UzioiXvo4PjBqu7h1aZ7UwYDGJL5RK2w=,tag:MdY08DI/u3Vesf6tkUn8bw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:XLiP/fdmfNKALicLT8Cm0j6pZoIvJagvMIlHzjP485eAb/CUBe+YHGRhyxM93CpbogOAASW7lRTlRrV/en0axQ==,iv:zrEYU2UZ5lgIEOQv3sc7P7o4PtqF6HJt8B4mkXb+/kM=,tag:eUbaPYK+LVqjZTs7FfX9xg==,type:str]
    forgejo-uri: ENC[AES256_GCM,data:WlggHuA8KclU5AoTRljnMTzdOVG8/NspFnDkkT/X4Tc6RZa/zL5WMP3GiU322OGOWsWU55DZXhjTIMgCSy5fKts+1cO/JnV4IICNDqOyJHx/MMI8srgwd5DsZp6bAN0wqgEzHmv+sRU/T5mDpl/K/9F82OHBOlL6jgiONua5Udc=,iv:H0HAWfornFL4IE0Yu5i2OHO8mS2L5yE1JUUMKnpgMK8=,tag:h6ZRrqHzgtsAxYWJa/hUpQ==,type:str]
    authelia-uri: ENC[AES256_GCM,data:BH97HhZ220fw+JvFjuNgvg38Vi76rFaMMuYFR9+mxdnhg5FQIZHEIeNQvd4wYEys+dqhUYXsm0v5rS7fczgSq1GMX40/Xr8GPHwOOWrtba9+rZl4kjzg0QDhHBrUP7cwc7YgekzDOclhr2hp1osr7BxkYydfP8SHbVf2tiThAv68,iv:HLbiUY81id3ac8ejKUqbGu87jQgBsngipJHq92baIug=,tag:QWrkpEMe2Lb6nMVppxKxGQ==,type:str]
    headscale-uri: ENC[AES256_GCM,data:f4UQ5gLQLWSdLEbZvevCU4LYdPLqEcZziY3Uz3Mfe44oMKUFZMIjmrSBAVGsHQ4SOzMoeB1EXTG+XVblA/eIN8jnUiKTKG2mpRXj8dVQkBTdtPiajgkMxQ+FfmuZXSISTIK8rRKseWlV19nVnmshXlhVqcb+YTF+tN4uSoLG9r0TGg==,iv:GRTV6V50PKzvNUjN+LgkAHf/Yro0+77NQJ4/hYyFZUA=,tag:cpNFIQT3HQC5uyLtWgPPZA==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMekJIbklJcFlHYUlTSXFz
            dktrWERKMVNVWjBidXJVUjFMbWMxL29kQnprCjZLZEVhUXBXY2E2RG5SU3RMODEx
            M3YxbThKNXlDNGUxV2hWNGZ3WDdZU2MKLS0tIGZoWFJLUUU4Yk53K1NsYy95ZFZU
            V1E4NFRHOFhxd0ljbHhrYVdoaUFkcVkKKwogbdcUox3aPv2MxdtT2dWpn0nC2hQn
            alKxRLCGo7RK+zmuCWhqfLKt7R/piy197PgSa4JZRJ8IDQgKsTozLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T11:32:16Z"
    mac: ENC[AES256_GCM,data:cIagmnotSCFB127P/XXN3JfloZTLTF5mduleijj+EULb4OK4AhDaNP9do1q2mrbXuGTlsag9PWJ7gGdJRsD0LH+FNoBB6+jqfzCLDxtN4OSpdJbVHk9z018Ey+DwftC05SNAOMIoBOgnddnmyRXVARSzhXVMKfRV9JywQMWUwqk=,iv:9SecITDTf8UvyJZ4ytL2hBi39IJXU8K3QqKa0XJmQhQ=,tag:/p94BOaw3v6wUnixbVIgYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
