apiVersion: ENC[AES256_GCM,data:f2E=,iv:7BuW3Hn29ulliy0CI8u0+dLWr42onHJCE9Z7F+SOMR0=,tag:BUgB6IkYgaRr4G/NJB7tBw==,type:str]
kind: ENC[AES256_GCM,data:FykcPNXf,iv:0yhcVE6g6CIYCebfMT1GrZbOvSOos/eGMCS/RlAAk6A=,tag:+WmIXMEh2bKkmV8j++vX3g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:O6uapOcvPqOQa0c=,iv:pYn2tu6thHF2BX5Rxq463AsSOJXOkICnFbvwxeZbZis=,tag:FaTdhVxRW2lHs7tcPH1b6w==,type:str]
    namespace: ENC[AES256_GCM,data:1T7MCQZ6bvU=,iv:NUoofgyQ1XQQzZhuTe34bkD69mY00HXALkIMWUpEK+w=,tag:rtFYI7MH3fVkVviavf3I3w==,type:str]
type: ENC[AES256_GCM,data:EmoL0JNzkKcKBt75Y8sZRY2nBIG/Jr7C,iv:u9S19tLd3WK0z42Hj7z1Heb4jhAkYiSsBP7iSzY/QaA=,tag:gJBKHXvhtcANo2zXo+fKAw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:g9yThfg2hw==,iv:8U9dyMGB5lU/VtJ84ppBWMnm5iw0B5pP0ZNP0UundWo=,tag:mvfgwfD+jCJXmKmFtLpytg==,type:str]
    password: ENC[AES256_GCM,data:hn3miW1rZ3ozQ5f8rEcuJ1zNgAQ5v8vCiR6L5D/QxPc=,iv:WU9NaJDM81XYJN2yPgkrvl6zvU6WgBmaAKttcmCRNi8=,tag:VbtUmo1zjD7RqXzhgo19NQ==,type:str]
    forgejo-uri: ENC[AES256_GCM,data:suVkpB3b7plPhl1W/sUur3vFDio5P+tuk9L7P1IA8lLUao7dL8Dnp5mhk/nMVWfBZturmNKIFg7U0UCuWUyCuSNPimZpGl7F2+Vt7WlDU8UUXpTCNAY7iAabkDMIhAw=,iv:eQKoUrEEgjki74sZwvw6jTy5eSXcuLuu7w1RiqVeK9w=,tag:LwMt8lf0ZGkVoJjEeXk07g==,type:str]
    authelia-uri: ENC[AES256_GCM,data:V0ASSDvAs5Jxz0Y0XuwUBcGkus8d9mxxD1iwCt+vjuvo8Y0d6sI2g4kmO9gClRy6tjoCJQi6Op0advDMOvIuOEKeyrXXZRi0r2ZdqHl9zI55ujvEQDRX6jCY9DhlY0Wr,iv:qSsrgeK4R4/7ftQilqKoLNAi/vpsfDP5tXd+x++cNVQ=,tag:CWNHeDGVivJxxLMRGl1djg==,type:str]
    headscale-uri: ENC[AES256_GCM,data:n6CUe2wm2lwESq8v+f3mVPEJfaFzFuIDzjKPkfQOldUXGF7t9RH7N4lI5KJ3sRZPQZFHRSDCUdyXe4tmNFXqsMDlYL7UMXhCpGLfHa5DsI85s0orqnDLwSfVizdczqp3mw==,iv:1/aeLSlVcgNAjKfeL1zvSNbJqQsky4N9TK17mmWYhbM=,tag:UjPXp0NNhsFf8yDtjiFgjQ==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OU1SMSszWTExcnQyU2Zz
            cW1YZXpWcDY5cGszYTB4RnRsSWpET040MmhnCjI1N1dUOUpMQkx2N2RTR2VRQndr
            dThtUS9OVVUxTWprNHE4eU50NzJubE0KLS0tIHFmazFDTU5sV0d0UUtGUTlHN1ND
            alZCRjRoUjJtaVdpWGtaWEZUMkFyTEUKlbXyr8Rv4S02M0jvFXyhj1ifZUet3OK+
            uCV7tn++6kZ+gGPfNeIFj0W2dNHgMhjgnbK/DdsKRBBMUo/OwDpl4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T12:56:29Z"
    mac: ENC[AES256_GCM,data:jtA7ybCsp5j5zypQN6kWpBu8RqvnZKNLTl50z6OxHBfaB/DzdyVbcYrccSecfqNTgfdE9tr5h8uTNWiHV1JMGRMiyqxAkZkAaMyyorVZ5n4BOYzeOsrTeyd1nM4PQI4jTf/p2gyLzLF9esAVyql7NJhXkT6uMVf9AB/BRCOovxQ=,iv:oFXU7V2ZDTkgvrWADkL1KzXegC079euag4Ly395fCwA=,tag:G0o0gmYoAQ7h+7FYWdPZjA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
