apiVersion: ENC[AES256_GCM,data:hHg=,iv:bOmf0o6yoEHRMG+HFz+d8mZ9ppdJn+N2zdnyeAcx9B4=,tag:sdWL+qngGCpFKvZ5POvQPw==,type:str]
kind: ENC[AES256_GCM,data:oEQTk8ll,iv:+zkIXEtL4gMh3LKgANyBfvdtfo2Xsr2/I4xIM9qbL4k=,tag:ob84UBQYB58Eo5tB+mpGeQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RzhlR6GgXpCUHLU=,iv:EdJsUwWlAT8lmdjLYGxiWduxV6RCJZCMblRuxrV4/eA=,tag:crrVxZZDyY6P0K0MLlwvsw==,type:str]
    namespace: ENC[AES256_GCM,data:tiK9yEiftZI=,iv:EjVjxIYawIld6cKvsDLhrASxMqWPCWEkcE22nhIcJvg=,tag:cMTfdN56bdW546VaEZMHSg==,type:str]
type: ENC[AES256_GCM,data:DRTS5kUeWH8saJU8FHNzyecpPR8byJMD,iv:5SB6HRMITCeRYwJ0bZiaD1cIvVjIdLxrnEkTCGgpGhE=,tag:Wx/1EO+8lYkTSfTgdECKkA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:M8zhjbvU+w==,iv:Wtw8fHNLWu/apCENWFSbo9hiBCMAlNioNFxDgyumNvE=,tag:mOjqr74b342XMw3N6ygRAg==,type:str]
    password: null
    forgejo-uri: ENC[AES256_GCM,data:mtt0ia3YizRN2e/NKvu5lD6+aCnVBcvXV2V4k/MCmAV1ATAqUezYZcvVuQqVds0vbVhYiFkxCLhZWG8KxOKh,iv:eaBxTUPyTgY6Zi46N+hnGAkfFrTZuRFXqmvfCQNeJfI=,tag:4/w3Ti5z36lPXaQ43a8Gbg==,type:str]
    authelia-uri: ENC[AES256_GCM,data:/O2AA/WYzsNzBuivOWIpU0VxAmp+9ZT+IvDJWLiWgR1eoa1JNlfjPPWKFm+fzzZo6EDnmSkYfxp45XmHASv/cA==,iv:agFYrX/ZzcU3SabL9w/WGcHgcrVXmSta+AtIftis8rg=,tag:+BVLw5Tf3WEj76a6DdC4wA==,type:str]
    headscale-uri: ENC[AES256_GCM,data:CLbiLrp74ajsTMAqFYeRx1uW84c+IYV2BiyULIPrlxlJXE97fpTD8guvnIIFgjDvKwzycKHK738Nq+lU0rQunDk=,iv:yH3cfTizFgX1tR9NM6AwoLGat4zKECF+YLlpVSmHTA4=,tag:K2cw5oqsG3ZTRvMMZOBrFg==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Rkg2Y3lWK0N5aHJKd2Jh
            SE1vTktjMmdWMlJscVM0WWg1ckcxYnFHcW5NCjdGemdKaVNlRTFiZ1ByS0F3dEQ5
            M2h4STllZDlxRitZWWxXa210MlR3OXcKLS0tIEtTck1LeVNFSUE0eHV4Q0w2Y1Jr
            VTQrbW9oNmZqWEhNTzdSd3Bud0FsQlkKCz2k+CPJoRLxYRHy60CZ3645PDKFkFZF
            XM6Uukdd0oamgtHZ0baziD+gGiwMW4018Siq54g9C16FbaYMw9gRNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T15:38:12Z"
    mac: ENC[AES256_GCM,data:lfpW8V5bXkIcCGkE1gKmbQMScnCsFFbvDlb4s3NsrMJEEaM0ADkOuUvCq0baQ3CkNUeg0941TzcyvOK5yBSlGthf6ROcW95bC50MlgID1IzXQ9OIg0W9w7zhgVTcWyADul9K4lGHOKedkoNgD3oO68Rb5Tnobwe6PIw7oDDzDe8=,iv:pSyB5HvaTBKcRa3UDMFJVPztrm1Kqx7UWApcM3AeVDw=,tag:cK39jpnHu/v6ExiL/ix5IA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
