apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: "3.7.3"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    serviceAccount:
      name: homepage
    controllers:
      main:
        pod:
          nodeSelector:
            kubernetes.io/hostname: talos-worker
        initContainers:
          copy-config:
            image:
              repository: busybox
              tag: latest
            command:
              - sh
              - -c
              - cp /configmap/* /config/
        containers:
          main:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: latest
            env:
              HOMEPAGE_ALLOWED_HOSTS: pedrocoutinho.eu,homepage.homepage,homepage.homepage.svc.cluster.local
            resources:
              requests:
                memory: 32Mi
                cpu: 50m
              limits:
                memory: 256Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /app/config
        advancedMounts:
          main:
            copy-config:
              - path: /config
      configmap:
        type: configMap
        name: homepage-config
        advancedMounts:
          main:
            copy-config:
              - path: /configmap
                readOnly: true
