apiVersion: ENC[AES256_GCM,data:wX4=,iv:CgeaWjNgQIIX7FMRBivw+c1hJ9P6fDomhKq8erq1n2Q=,tag:lRB+yjvZITLSnCyt+jFRyA==,type:str]
kind: ENC[AES256_GCM,data:HNScxW7A,iv:7bt3Se2yDlJRukXg9jhvHeiy2AS7qMD5rvt44G4uOQ8=,tag:gKYVYPRlrBDy8DGLbHVcpA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1igXKqe5do3ew4H4P/h7WTtaDgHZNkQCOw==,iv:Wsrt6lneidZR4rsxIlsByJJ6Q3RJb2HhdYKg0FmL+C4=,tag:Qs1COgaAlhH7PzQ0Ozgyiw==,type:str]
    namespace: ENC[AES256_GCM,data:GRr8QxYmp58gtDo=,iv:ePkxzIUWIkYUOG4iJ/92R5O/Ry48InFC8ouGzFn7nKg=,tag:hIkA6kzKdeBk8OK/rOTk4Q==,type:str]
type: ENC[AES256_GCM,data:y/0XpaiJ,iv:69iklLWlXrz4OgYQ/mv0SmYiFDprVCE6EoSjBz6S+js=,tag:yMbouA0wJS/okBpx1tndJQ==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aXL8a6NGxG4GbFalEMJiGGMGG0NOXRByIw==,iv:080O9i/RhC6/3q/DBLEulUsg02SMEEQpMRTebt5BN7Y=,tag:g3zg8x1nL+wJWxS6dZTgNQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DxCcFmbStf/Yb4dun9bFHopWM1RIaPbLGWpVLHi+Kw==,iv:ZrFIcCNzEVo/kS7/tJLoCGlW4auFttmnwiTnHnRI0L0=,tag:5GPf6YFoHjtUxY1PDhjg+A==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:PNJIVqTAvjyq5HU/NF6V2rz2kT9BEj+NdpdScycOf9kyEC3vQiWv1UjzUHepe4o6JzH8LzDsI51y5VR5pitNbbAEkRO4MGvrpPq6wA==,iv:1d4qrM9RhK3WMPWNVnRac74AQnLY0tGfXBRpDkv4oqw=,tag:V+JPVoxv6ZNTSuIMmjJ7ZQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:dSkvaZ3piWcNxp2vxTVxrmqdgW+gWvzSqe9pF+Mnt1a7C4ajFl2CEs59wPM=,iv:8cPeWXyJWCmPgVhN6o+iEQ58lPsGoTR1pjNxy0hJmDk=,tag:zkuhkludzB8lI8sCrQAw+A==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSzBhOXVPL1BVczlUZU5W
            NENVamkxNzhVU2NXcGJtV3N0Unltc2REbFQ0ClV6NjlGRkVBZ3puV1dQWGJuRGs0
            QUlxWEVObTJlSjhmSGJBR3Bmd2E3UGcKLS0tIHVHZUZuZDJWZ3I2L3ZGeld2NG1L
            YjVWWUNnSGI4M3BYaUoxRHpUZlFWTEkKtlXblX0L2jU17U0gkPVjYzag5vdKpLzY
            7MfD4tH0BgZLE7gmQoVG0hezZmyTqfc1jj5N7nrpacahmRBOCkt5UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T14:39:41Z"
    mac: ENC[AES256_GCM,data:9Cpfr4MEoK4LyZ1BWugQ49WcHvzmax08MrnKR5ELOdm99kzgit26ME49aLxYBiX35JNsQ3yE8OwfsjhYUUizNTmRpV88LsZ9AUD6PqCd1RGmzvHdJ5afoh/TJVlkk3KSR72cU+OuxfZV7Ei0II1pzEayIQgwcarRBIrb4gmm1x8=,iv:wM7U+9VEh2YvLlhRv9s4nsA8dw+mN/1XyLX5/iBicyI=,tag:POw3OVSButbruffA13UiuQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
