apiVersion: ENC[AES256_GCM,data:xZg=,iv:sPMnoHapA9wjRkpJuPlON5HgnyWA8TnelkIIF22YyD8=,tag:HPhwNbymtlEzD6GA8uw4AA==,type:str]
kind: ENC[AES256_GCM,data:uoFhVuad,iv:wA8Ok2zm0nDf3/SziyjH0f4tA2w5wexooellauO/seU=,tag:iGo064RQjvtpewx7PqWEuw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eREm2Xe5SSbCB4S4KIR/rpUcALqv,iv:drLYydi7zQgTgVM4no9EmAMgnA9Yi2wyrd7VrHsiLcQ=,tag:B/IAdSengST4klzfHPSxjg==,type:str]
    namespace: ENC[AES256_GCM,data:yRSt0+QTkUvYM8c=,iv:tnGr2sks5UTXcH5ALyNlhADtYkLPj4Mq4RKn4DQLccE=,tag:csL+x9s6f+ibG6gy/piJDg==,type:str]
type: ENC[AES256_GCM,data:FQcEuZ2P,iv:7bSZMyyWnwnsYNBg3+VEA5o+hjjzAJFBDtM8XaEOgsc=,tag:XY+UhqTp32l6oafmGY+EJg==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:EHrThsWlM8alb4RejkVxmeBc/8Zp0cwVEPIA5XuRcn3o5M/kWO0DTMk7x6eThXU5BrH5QugEo3Rnq1HQoaq27ix5B0tsqNaJ+o2Skezl4vJ/VEkyOLXA79sWuJI97teAvBS0BnI=,iv:l1HqSuiwsmTHm2F3uceFl1vT7lrqbENycuYpxxe5+2Y=,tag:JVDP2ZzHZCxSd/a/wccwWw==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QUFOdHAybnFUZEZSN2Fm
            QXY3WjFIT0RzKzIvRUkxbDQ2UzFwNE1TeFFNCnI0UkRxYXIzdWNIMm5YODN0M1RT
            NTB1eHZlTWswL1k5bUw4VHlXZE1vTjgKLS0tIFhDVXkxRGZTS2lKYm9ocU4rNVdj
            TUcyMVlWaW5pUThuZXgySTh1bEF3Um8KhGk1+RVDNYPiA0X2BS0pZWbjrKKffjLK
            8NYaENILZFrBU3f5Xax1Ld4CdFmD9wrysrfR8121pHOXZEZSGmUAig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T14:24:44Z"
    mac: ENC[AES256_GCM,data:+QBx1uplZU+YGHru2iNU1rBE/DEom/elxIQm0JkhFYrpATvfCSkwuAuScIEHBVQ17uj+IHGrkqJ0nL9RRqyPWfc3GQ+ygLpCr+35YOS0Gpmr7qdrfKGDbaSr7d2WlUeeVM1sDQkHpVws4omokBGMx8cz0E+KcGm/0rgBvMZ2zNk=,iv:s10AQYnnNarQ5I+ZHMQsVid1vEjOaq3fMq+pKjteelQ=,tag:vWRnFtGG73HfAaaciZwkcA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
