apiVersion: ENC[AES256_GCM,data:ahU=,iv:Xk9d/XcTXoQIK4OAC31T+s/LUcQ4m7DTgMoE06vckqI=,tag:uGdnrkPdEfxwix1hdDtoOw==,type:str]
kind: ENC[AES256_GCM,data:JSlvPYPO,iv:ZnFrsspXoGlTnNwcbYDEmv/pbSJGFGq2pe5Ib76CV4o=,tag:WYs1Ydz6rkk7F0JH495jig==,type:str]
metadata:
    name: ENC[AES256_GCM,data:12e9YrwT9See1W0q7GOEpmO0SLRq,iv:aq8inr4r9o9Davmt4+B4KcMIEckt69U3BjvNL2favY0=,tag:jiZZ6/EjhcrjC+VYM9jEUw==,type:str]
    namespace: ENC[AES256_GCM,data:uYlokQa4h9vcecw=,iv:o5WmuTvbDyTCdOVM0hHUhsudcCUo2kmO/jzIoJVzSPI=,tag:0lzX46Mj7GnrQoOA/m1MRA==,type:str]
type: ENC[AES256_GCM,data:L3itrELp,iv:P5t3TbCOtAeEZXVO07zRuoFgCReBAs6+wG3HQ5Dwv0U=,tag:P2MXw3B6gJjOgx405y3z9g==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:GmJ62emWYv+A9zRkXDuIm6vyPCbdm4FKAlJhMUuRFUzqYfazsszZsGGhdqP09ZwxMyPyThLoMEIgryGq3k3NnDfzX21NWizvl1pLdp7koJ/2bY2DMT+EQMY+hINJ7ElEsBcDpg==,iv:e6teXNusW94zbOGo2Pfi+cFgBR1AsHGyWRRklY67Kck=,tag:C5uijFYaivhShaEm1R8aew==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYnk0VkJ1UjJGQ3Jlbm42
            RTBUVXdNZ0NRUGZYNUlSUnpuWVg0QUw2SGo4ClgwY3dSVjFyZmpDTHBvY1M2S2Zv
            N0tqR3M2cktNVmNMODRzMmJYZjIzL3MKLS0tIDBwM1BLbXVRQUVEa3VVRFI2MUlW
            SmhuS1JaTDg2SUx0aEYvaHBzOUdTQkEKt9w2Iit9KznAlaHAcXUVc6lrG09q0Onr
            WmDMjs5YeUbMmW+5YTBR4c8itmYf4gx7SluEue1jUZGamXC2m/Na9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T14:08:24Z"
    mac: ENC[AES256_GCM,data:2Xf/ajbTnoW/sgDqh+THnBGL8JvBr8dJUlvl9aAwq7PVuUR00yHgEmi9LSt9F9rkBdZj/GdeAq+voCL2+5UWlsjvED3ysu0Ml4cb78wa8PUsp+WAV+PfzEH6bsSZ6LaVdgLK7NN1MmiYTTCg1gk1HibPFtW5rV4W+FSxp19V2sI=,iv:pm791sdmnDbpHMLvZ7iu8esyDGYezU7iEZrGMZPP7nY=,tag:IJoLFgMk+rRmlaA+LBVlXg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
