apiVersion: ENC[AES256_GCM,data:hsI=,iv:lsiVOa3mOqnaz0ITxn5PKp/QVGSjohtucK7MSts8ZuA=,tag:ELcAPh8cOgQkpGTbfU2G9g==,type:str]
kind: ENC[AES256_GCM,data:BfYxzXtY,iv:RF9K5gCyGJZSIX9wJm9QLnvzf9TSO6Tr0877uKNocKo=,tag:Ixg3eBS5bME4Ot4mZiHLug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PWkXS1gqhItEn0KiKpnhIg==,iv:8EjTSSpaA5a2ArrgzxSV2yjfDSxZCb7P+UpNIa6epNs=,tag:/1tAbPcEJoXBei4pC6zPqw==,type:str]
    namespace: ENC[AES256_GCM,data:agGQGCXm/XZJ,iv:Zry3DH1e9eisN4d16JORp/fSydwfnrpOWfvkV63XZTo=,tag:LPZKbxjSGt+ik1jml2zDgQ==,type:str]
type: ENC[AES256_GCM,data:obKWHm6Y,iv:nvzxczJcrlYPh5IA5AaoZZbgDaAohzwoNSIvSNMPy6c=,tag:JwtVKq5ykTdJaCxODOdzsw==,type:str]
stringData:
    HEADSCALE_API_KEY: ENC[AES256_GCM,data:JYnI724Wu+pIPOhflCBvTi5j9z42Amxjj4nA7uYvs4nlcu1xhK0gug==,iv:vQhW45ZP8lBUYONAt7Uh5pV3sE5L8A0/sT44x+NHIMg=,tag:luxL50XgbkmAP8kazLIlUw==,type:str]
    config.yaml: ENC[AES256_GCM,data:bSvWO8yDLtrHICfzQ6BE7uc0ixAhheLrWO1idtJ+w7e0FMmnhRNOBVBGaxME/8uaDH335y8qZP1ZHeUVbSkyr4ZV716wGe2HrEXaxQL7zqj9FXAATeQLmGSOEAPHzMC0Q85S2FsY4JjKr32gqtW+FMVFykziEXdmVQUUQkj5nLObPdp+gLoBAiz9BLuUt+7k+VNUWPkXDo3U9d3Lzrl6KX1+fcVvgXglh2ivYU5R339Pql5abIDtrff+X9LrNZ5YPhwZbW3yUZWufCIEbh8r+JI+21GlZsixdInIr8qMMeIGA72xZ5NK2xT7FVF2FTt8nEbqBVwnCOM1K26pgnSnP7U3waPUJOliBuJoc9UZN82YRmkg0mcV6NYt156MZFgZlcMmR1nXqsa0YDQkt2n1eCi8SU5b+Op14HR2mCWs1nYekkQz59dwUN4UOhidO3t19gjJRntBo0vLLxeYsZNfw5Pvw3MIlVutmCHSlk6NGV1e5WOhSx4TXuGJfsV1bPu++IVCbN/9Yl9H0ZDIF6ap9guc8H/xgQKbwhgYozCA9FPMoHxadKqM7Nb6+LfkX03Ftzc2i38iFc8EPPq7G3vYGh+zj6aqe9tPRVAzI//lOYRqxNbABeMSlnV0yJfbpMc6w0iAT8bWEHci/kiyfOD4UthE+6LUxJWck/NdUNWI7nGNsjf6kw6AxwXfVRM51Y8LuWAGR1t347hUydzbwrE5VcrH1Eeqwl9agDA8jWpsLLHnb21Fq0ohbcYz,iv:zN+L5dUehh06m2AUng5gQ6s1QDYj+JkhoPcRWi7vcbs=,tag:tzO1QktkXwL3CintLAnoFg==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlejJRUEhUMVo2aXBwdDhi
            R0UzU0VBMFZPREJTc2JUVS9DbnNPVkx4Q3hnCjF4ZjBrMWxaM0R5MThYMjBJL292
            dXpvVUVEK1FWcWkzdFIySXdLRER4VEUKLS0tIGVEMzVXK3RwSG9iaHduN3NzWFNl
            eGJLNlBHMy8vVkZYaE9WYUVVS0Rkd3MKboiE5Qy6KxsHR2c1YS1/Oo8NdZitFApj
            /FQkNNYlnyzAW3L91ikvJn4FfKWB7CnHT2vFmqhx6XcLvaXvL+yofQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T03:04:58Z"
    mac: ENC[AES256_GCM,data:t/gvdCbTKgtNE0bpygWQf9niNR6WCXnujlJmb1hsuwgcXPJPj5yblCMRJCJeLv2VWFY1t4ayKqNiLKDxzoxnGmeVmhYMRWwTk7WdQv+1cbt8Wzwo6/dQnl6q6iNe1f0gdTQUPNJgnhdRo9O14ZdY+LdpuelwuDU150ENQ5MFNyk=,iv:UHn/sBNtmdj5pb6zpU3odY+hxGCPbgn5dq8CJeWN70U=,tag:euBxUvrUBt1Dx1bAGcE50Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
