apiVersion: ENC[AES256_GCM,data:ylk=,iv:6lmV0f5vEebzHyO38hO0k/Wj26G9P/W5NQvDctYrM8E=,tag:s9l+9BsIPxf2M9c/yjf8UA==,type:str]
kind: ENC[AES256_GCM,data:PKCCmtA/,iv:3Oi4N/Gx4MBseXOh1qPIWepqS/gg3VOrNtrUj8tDR6k=,tag:Z9iCXkCi7SDXsA7bNK3KRw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+uDCCrn5fYk6On+bZwCOsQ==,iv:ge+eguNxepZJv/JOGplrw3IIKxLdCGZ/FXPbpyffCQA=,tag:z4wbzjLbNni1u39DYSPGJw==,type:str]
    namespace: ENC[AES256_GCM,data:kalgC7VKpg8P,iv:IwRdKvWkUOZgnORFbKS0pjmreM/hhmcCb3DsICzKTaY=,tag:O4S2EyvmufVlBoZI7ZdGvA==,type:str]
type: ENC[AES256_GCM,data:hkQ2AKei,iv:j9sEiKMfRuxGl/CA6nw8rHY6+mskbVTlmES4F3lEiQE=,tag:phndZz68LgvoNgt+06jfnw==,type:str]
stringData:
    HEADSCALE_API_KEY: ENC[AES256_GCM,data:2qrY1CU2MrME0WTPivhAdzMQf05v/CXVYkiTGW0tyquB7I9P6bmldw==,iv:5olAqYLMBsMQXNhtwHsy2P2ldUMl3X5NdRCAWBVSQrI=,tag:Dn8R2fOuN7LSO4JEf53QXg==,type:str]
    config.yaml: ENC[AES256_GCM,data:KrCnFKMhEJ/dWLx4mgaWTEUas+XyzwB1OqtzhZ61FMYy49T3kSt5yA57IkQlRY/hM79mE27JgDd1IAKkfwfqnBkUV6OByfXlrO2r40gExl6gdXXYEntPnJ+nJ3H3kYMEweHrzD1mJYskRdVpFl3pWi1EC+Jv/ciFOhHExTlpiIg5Q/NLNO6zhvojOyiVJ6yiPVfqSLbFSi9tuzMpCLjRj78v+hW4ZKKFLDaH0snp9ZN++tibsg9sy1Ob7bqxVI9uM/lV5uu3w0lzc3SgRgYqk4tkbqYYTDZiIYZmomAzMgqDdsEtTJILevqsAfG5nwFUKhPDked4Y1gNHBHvqw==,iv:qbgRLgSd9hN9uk28AFdY9ZJmFlMuRxPJSmd03kcUhrk=,tag:i9xtS67KmQxy7AFqNq2sGg==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5U2g3QWNaVnYyRWVCWk5i
            aGdnQWgvTzV0bGNwYkgvRVlBWWpTZVM3MGdrCktEb1hEQTFkdnBOQTBraC9yalJr
            citISmllWG5ZTFE0NTc3MlJOUTl6OFkKLS0tIElZQXFxZERscVFhcGZrdEVBdm1F
            bDJVN2xGZ2o3Z3hWaU1LWWViYS9remsKOXE7jlOKwG2XzfjhPweID84Iza2A/zl5
            K82uHvwd3XD5Bh5kPcikDOx2X4NXRP2Gs8jp1nlYD9B0LmWMPfHfXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T00:40:29Z"
    mac: ENC[AES256_GCM,data:wDBDQvFBHva9Y2RfPtbyGlotua6AyL61dUE33t7X4eefwdhWIFEiCSjxXkSMLWLkga7s7OoC+VLJmDCxRudx8ZUgE0p/kbTyogY74qFgn0/aCz1m2BitJAz+FQqsNmu1kbsd9qX8JbgiKO2d88x/C8yezj5JE7kQyM0E3Nx8AIE=,iv:6Pe+blgkcPM+SNGiGVAEb0vIPMps2BZEFwqZAsYAaBo=,tag:mtQ5QbUKiBvBJ20FUELCgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
