apiVersion: ENC[AES256_GCM,data:AWE=,iv:fnzjEK2P6affRzOyESqW0AklxgRQTsJXd29R3Mg2w4E=,tag:AZOLG3Ux45nQ+m7FgWPgaQ==,type:str]
kind: ENC[AES256_GCM,data:3VMSwi8p,iv:eValZqvm6Fw0nKnekXb9E9I20Gbd10WhciOm0zJQsrU=,tag:4xGofgP1y4u8fsOoGond0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jST0m4Y1fa6p+FiT44JUmw==,iv:Hea6rngLOUDcMfJ/fpdyJK85yMtCIimC8j7O+W6Xb6Y=,tag:z4TRZoo3bM/QScdBmNuB2A==,type:str]
    namespace: ENC[AES256_GCM,data:6jOfPZExODOf,iv:0Vo0WWrKroRtVcMyTYzF/5F/Bcwcha7UmrAmSJtlz5Y=,tag:qIZ92TlK63ne2CZpXObkwg==,type:str]
type: ENC[AES256_GCM,data:tS+CMHDA,iv:bSInYpMGBExrV8Lo1xYng5H4knIBC2JuDPgdqLcLygM=,tag:meBZ6+h7rzUIVlUHSYNMRw==,type:str]
stringData:
    HEADSCALE_API_KEY: ENC[AES256_GCM,data:T5s+S5xxRqeW4KIiKmfG6hDRvhwANyRGhstC3Tl1//6mxStxRQaLyQ==,iv:mcp+GFSr76inUUvL1z+UBEW1rIg8OlwSHb3YoTOovIo=,tag:e7AJLGdlTHZ5zYRyyi8cMQ==,type:str]
    config.yaml: ENC[AES256_GCM,data:0OpZjkTgA47XIEP14z/VP8X1Rti8bHl9worEH7bC9FlZinYaFBBan064Mcnnhy1+DQ0cExQdWToT39ZjohPlFhb8+WBMG0/uLB7GT7+h1T9PcrKs1ZUoHPMgaCX5lUeeJiPtmzqRUi+M5auz9RhbnGZT/blCNXVABT0g8uxiN9FpUbzSfV8AZfP3UdlYtUpccClI9FVwX9Hb8ZPgxfP4FtbO10WVPQi3mIMk4CzreIGNTeNEw9l9oiz4qKQu287qXoL8jrgsz7rwpWBBz9vii1adndCsphQtRMV76+bycoeHpbuw6A7QMvGTChx/Jxea2WXqOEdi+WOHUwVy3K9Mu1GSnn4xpDF8esGChPv9JfHjUAffFQ==,iv:FHUdG3fyAHCkBW0Kcqhzgdm7YU8ydMd/lJFVt/F3uPw=,tag:HpzZjjk5qlFukd7GZjXDrA==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBanNaejdyU0lFZkluRjcx
            OUpJSXp4dmdDazg0RDdYZDZZMmNpVWxFalU4ClhmSkxkU2lOMmJUdHJmWWZJRlB3
            MFVCMjloU1VGam02N0VlZFowRkxYcncKLS0tIE1Vc1p0ZnVLY3RNUEIrUjlDampT
            MERabS9pU3JmOWhZT1dpWWxnMnI4YUkKO0y99B6tzteZsdyTkiQ1yO48hGqlVJE/
            DEcHqvN0I1+T5FE1LyWFcOz/nch7yGasOodwJ+2FBhLtKrRm8nYPfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T00:45:25Z"
    mac: ENC[AES256_GCM,data:6HfuZpSJpyvEkQWPMQtt8o6z+2+04MZEdBGhC9knegHLap7uaYjKAukx9fkSIdcWDZf0cgrT4Z0eEUuNwXi8Yxr+y20TZvJQrLO9GlxJorSUbmif7gOO5QyGd0Ca83nCg316BbaB27skBX1KJwe2/wkQGuyO0lS/hBaqnBv/nI8=,iv:F5xRR+eNAUGbU0S6J0fsajIhD02l0zLyRb35VM55eg0=,tag:8vDNlAsnJ7NzqLB64++CGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
