apiVersion: ENC[AES256_GCM,data:syM=,iv:4BwAiP4TfCFQOzre+n5KZk9m7bv3w+8SF949LCMWRq4=,tag:sA4tZLBDFg3rpjLbDwClrA==,type:str]
kind: ENC[AES256_GCM,data:uIFHp0oU,iv:oYcUNyX55piBJ7pu2Nj5YdE4p/TUeRbuQKZKKGLVlR4=,tag:7ZjebAyj0AA6UCW1bjRUMg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Dh3xr9U1t0qgUfF1OI2T2m5UmPhJCsU=,iv:yoFR3204U5Gnd2LFV/XTkbf0UQwMcducHN5q/4pGWd8=,tag:twZRaEERB511VfESKsQrKQ==,type:str]
    namespace: ENC[AES256_GCM,data:11DFYu4I+p5f,iv:KB8sni7W2582jYOUl6GMz/OtQzQ2QC81d5xL+Msq4qg=,tag:xlntLfcrhQ/KAIBXD7JNeQ==,type:str]
type: ENC[AES256_GCM,data:txoJaF1D,iv:9RzubdTrKMFMcUa1qf/ipEBDRBOVK8fvBwjBQ29yOwg=,tag:Gc3K6kohxP/6YkWgy4pAkA==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wtika99g5BO/IaE3Dkt8nBbQmCD8IbC6IA==,iv:k3XnyPfKYz/UyrbQbZNJBKRYVKXpdI4nrlhIHDwuJdI=,tag:LarzKY9Rs0zVk480NrqPtw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DR3vams4ar3xvRmf/VK6IOP+fdSXUOpLu5kuprYJzQ==,iv:Rg+5FG6cSH55lzJqWrC3nSXMmIMDe4gwvaeWkDQaxf8=,tag:SGvkrg3Tk2IAMRwnnMpMYw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:8VX6hibuFYvbv0oeaGd3zAQlzppsjzVynoU87GM9hTBe9YX+cGIpZ1oTboMLhWgHG0TviaUewdP1Mgdr6mt5SXYKm3dZayc+mWY=,iv:2xcZugcmL/wegR2vw3mjlBLxSoF6uVi4/F9HMH9wQWQ=,tag:k+/HAfmy6tcZIsdAJr2gOA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Zcu+PTjk5HOV+HWpD8+VFuZ2QBUgNMvC2cIzzWv6oU8hon7XwcTpG9rJBnA=,iv:fp703RXMafLbtI+uVKoC/AaYQZV6YHdOWD0SAQ5/dWA=,tag:TI+Exxz1AZGx0nAqyWjxIA==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSGdRMGN0aXFQNHp5dWRR
            S1RKMW5INlBsL3JJTjh5QXRLcEFHdnVVV1dBCkh3QzRXZ1NJQU5FQkdZOVU0WXNV
            Tis2UWx5cWd1bkQ2K3pVR3lYblg1eGcKLS0tIE5nenRQcTFqeVEzN3BMM3NyYTB3
            NWJFMU40bG45Q2NKVkJxR0ZLT0V0TlEKoM9sc3DkJnMPGhZAHSSUOoG2rtZ+2//r
            vuFNN/PTkEfCK/bTfB292RAHQ58likkCd4DhA/bqKrxpkpyHwpWoqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T00:58:39Z"
    mac: ENC[AES256_GCM,data:uCzq24YBRfOJfPGQgQNeGyL/nPuLMTctXejT3OJSoofDjU2/wbKphoGdl8N1/zIDkxPHx+qh6v5FAZwY1ItVmG2r76/pk3VHYuNupIX6hDi7CE8FJCNvfoo31QLrVbqM0RbAJiYbrAfFn5vkQUJsBf0Kwn+IJNHKFNj9jQNgQ4Q=,iv:a6b7LZUPiiYYKQiPWGQGC126EPPX121e04Eskx8nNqo=,tag:9ZlG8lQ6SYlJPnE0dfESfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
