apiVersion: ENC[AES256_GCM,data:Zks=,iv:E56mTIlac0IDkKxnn5k0i0s9owski/S5Kp1xxo1PHuc=,tag:sl4rylL/olts7V3STdFKrw==,type:str]
kind: ENC[AES256_GCM,data:cEKV4XID,iv:oQQ6ywshKKx6pNwAQZIPcLD73K6U+da2K+aRm3kC3a0=,tag:c4Zg+FfSk7GiuQGhm3n8eA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Uh/Rx+YfLDfybnYjmu0Ix98qNI0n,iv:Tuu6WRoEEFbht4qJk6JPxdEbMsurz9gOAuonH+FwLgA=,tag:IPVctRT6IWGQe4G/wjd4xQ==,type:str]
    namespace: ENC[AES256_GCM,data:Zezo+7Tah01j,iv:nXeyJZ/+yfJHmsFElv0Ff4Q9SwY0DtbOxpItnkFu+8c=,tag:X06QiILSCaV4ixQ3wmEOcQ==,type:str]
type: ENC[AES256_GCM,data:J/8l8h6f,iv:ks2mk6Lc80UeB0E5QfIrf+cWMOBdS+PylcU23QsrTig=,tag:gYBAcL1lPskgNMMe81cYBA==,type:str]
stringData:
    override.yaml: ENC[AES256_GCM,data:nWGrHCfqSkeK/EcTcmmwNPJYBhxh5d9fzqgxLCZsPTsQ+6m3WRW3lpCIHYzz3ejJVpy7a4hlB0wr7mnYJ80kuQMzMq4pPJ8isbP8TdnFc/6vwNlmofnlsAJPSQl+bZaf3pXqmTlslgVt3H6/Lg/Gy0eNEtrcTrDrOkyT/xBA3rxzKitW7OXKw6tabf9xv0PUp5yJlYQRKSKZ9slVbF9so21YVDiCRrZIF/11SQsD08lky+vp,iv:C0ZeLNTSvsvADrng3uzpwSryvpZJB2MHQEsRB7pg3Ng=,tag:08cdN2BHp+7SGaNNHRapyw==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSUVRU2lwNFp2cXBpT2Zs
            WFRhaHlCYWhlTTB3OFlpbVM5NkhwK0xmVjJZCnJhRFRCcEs5YmZNRnNoQUszQTVr
            TkxITkE4MitrdFloanJWZGtzSVlUMHcKLS0tIFFtcGJ6OWw3TmM0UDBBQVVuUVJI
            ZlhlQmg0SVVySG12WloxUEU0TlVOaFUK5MW9egFh9ddm9j9OFIp/X5EtdW+MjqG3
            Hmx6Eo/Is2bUdJhPdTQpwiUZ81Dxa7ahf8Sy1O3sgGVjUdYhPs3fsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T15:51:39Z"
    mac: ENC[AES256_GCM,data:QOY5lN0lmeJUoiRqfnX1KuVx/NGJyx8TS/0xyW4I0b90LaiSrN/AXCZMuy/AY2NhEw7rHtqPqJqAzy3iaYyDJdeftq+HigT4U59le+64LI9ikAhggODY95bpAjQjwXW9ILYQuQ+cb3pFY9GImX0BSlTMupqMtObrsgN+jrSC44Y=,iv:RxiFT3lfRXJ8Y7kUOjll6XTvY7QFSOOWQ6DWvhAN4Vo=,tag:WadXZyToHG2qPN77++tdQA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
