apiVersion: ENC[AES256_GCM,data:Fns=,iv:RaAOdbiLlXZXQLp0fESg5sisP8XClbW+VwS6JDh080o=,tag:aon9GpyrB5x0Su57tQy/2w==,type:str]
kind: ENC[AES256_GCM,data:0yU3D/ln,iv:JAZQVlMCjeYCGvA9xUEka5mO6j59S3DOkOb2am+md3k=,tag:JRcpljM5PRKuGCJ+31/SEQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6T+zwEpn6TZPSRyEVjo4++MSFQ==,iv:I7m/9OIUVDtGo3qMOe/eePalF34Zexx5o/HrpDIYu+A=,tag:LN/l8IudYit/BcsqMJ9FuA==,type:str]
    namespace: ENC[AES256_GCM,data:FZJSGjngLB1L,iv:61ujIwgkoIzViZK8MB+hl9MrLWQZsd9Rwn3StdUt6js=,tag:F4N7zSLHpnoxKQTRcTYIsw==,type:str]
type: ENC[AES256_GCM,data:nujh2XA7,iv:GNF7J4xzJ+ZreZiFGYddiRNl/BBj/uMoKFT6HHsApgo=,tag:l0kdmiZYfLaPW34X1ugWvA==,type:str]
stringData:
    password: null
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL2VnczZEeDR1Y2xybVpT
            ODJvK1hERHZieWpWNEp0NTZmVDZrRkVWb3c0ClZjL0FoczcvK2t4ZEl4aHFMR3Bz
            WVF3RVVxVmlZbWxidVdOc1hwWUc2UzAKLS0tICtvWFlSenpJT3hJbEg2SnR1enFq
            TFluSUpINko1ZHVGS0tBdjFWczFyYjAKcFPySPGQVndBpJCSbqQ9VTd/m8SDEuWh
            l4+H4YFxeDNR+nYPPffRwHzSkPTU8wZTJohqj5WNpiiXVJRihapSbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T15:38:10Z"
    mac: ENC[AES256_GCM,data:o+IhdtTo5bEez6uWLF8R54en8RQyo7BdSfhfnAxXO6JOpNhEupCAXkwRGDneNjmSObDxweWKA3XQR5rjp4UkEGrDlQM7rZ84prHRtrF/6wXHam1+P/Lm5QPH9kxxKD3/FPGKU1d0LqDR1md7HA4x9QuoLxMehf34bw0/tap3kBI=,iv:0zIaHmTCInHeJJXTJYPBA4VSS5nYul5YRfgPrSxigt8=,tag:qfrS8QB2mRqOgHcSkRgmpQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
