apiVersion: ENC[AES256_GCM,data:ESM=,iv:WTKG3GMR23xAVYp+AQ9xs50rWS81C29ZYZrpGXsJ9YY=,tag:Wq5uj9puA62SFSP4TkXZfQ==,type:str]
kind: ENC[AES256_GCM,data:Q/e93T1l,iv:BX80COUfbSJh/S8giw1G4Lz8xupHvMd9qYXebfwuA4U=,tag:C4PUcqJEDV7IS+Qk0+rmSg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5smEhWu9UaJVcX2wpl19I77HIg==,iv:+S6dL14+wJVbPFP+ES9Lq/I3svRuZ6ST29r/PQebL3E=,tag:nAqNCoJTA9blpbtQo3rUiw==,type:str]
    namespace: ENC[AES256_GCM,data:IERzGe/jMTrm,iv:wuVFi7vdzKHqT7kYD5FdvBuZu691ILw1tD1jgQsVRAM=,tag:8r+osEibWByjuR9hIcZrhg==,type:str]
type: ENC[AES256_GCM,data:rspBeeMy,iv:8shmb5RGyk3hXTZ0M7WTan0uImJ0+8hWVsPb80dmau4=,tag:npR5/wYZ2sVQaLO9Pmn4eA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:LyewRalApkVDy1/eEuwsx9RQTRzNwWrrMTKEVpcLVN0=,iv:gl4bQhoSXShGLcx10PF0eCpCsMGOyphjx4wE7HRz2sE=,tag:SylrXP4fQvcynT+Tlk/2Ag==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd0RQOGpWTmt3Y2FDK0Z6
            d1dkZDJDWDdMdmFrSVZpWXRkbVA0SXlKdHhzCmQyVWkrS2VTZHRreHdkUk04dXQ4
            dW9xR0RxV25iQWJUQ2YzYzV3aExPeUUKLS0tIFhzcTZIOUEwRjBFT3djWTZJV3lm
            OTdWSk53TzErTFJNRGZ0R0R3U3N6dlEKZhC2sf9HUD6Ghwng0RJo7LmErKWM6Pxh
            oiahBwxyEcK15IR1geL7+MPk+gEOXrBfSS3I2/YV3wGLn53K0F+dsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T15:17:16Z"
    mac: ENC[AES256_GCM,data:kPo8wWGSRkjeF7ATck7geyqJSqBNYodWJbqeUBEtKyKs/yXukkuB4WuX5//kwvy3h9+sin4TZh7LL717Mo2+xBDxdUE+0l36AaHAGCWuVYg4UER12qmb5XBmv03opP8tvcT/lOp0C6En1xrulcTUMoSZiZm3OtK7QlJSuskEZac=,iv:TSkEa86K3HvLkL+SEoSaO8V6emCtVWn34D7SXj9ynOs=,tag:Z36bHr0GjkJb3R0qTpC/GQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
