apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config.enc.yaml
  - helmrelease.yaml
  - ingressroute.yaml
  - backup-secret.enc.yaml
  - replicationsource.yaml
