apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: headscale-backup
  namespace: headscale
spec:
  sourcePVC: headscale-data
  trigger:
    schedule: "0 2 * * *"
  restic:
    pruneIntervalDays: 7
    repository: headscale-backup-secret
    retain:
      daily: 7
      weekly: 4
      monthly: 3
    copyMethod: Direct
    cacheCapacity: 500Mi
    cacheStorageClassName: longhorn
    moverSecurityContext:
      runAsUser: 65532
      runAsGroup: 65532
      fsGroup: 65532
