apiVersion: ENC[AES256_GCM,data:wEw=,iv:/fGhc8OFNsaE8QIYx9N4SND2v1RDaYsu4GkqTfhtdLk=,tag:gis8WjXohuKusk4HZa0IdQ==,type:str]
kind: ENC[AES256_GCM,data:VPxlzi5C,iv:SzIHluC2A3NaC/fO11LAp7Yq0nwf4tlBzkGXR4xwnGw=,tag:Szx9Aju3WU9uRSvkMZiAOQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5yTra+0DjxJ9e327G+t04w==,iv:kXF/uMvroXNmpdH8/n3YbNAeyJCDUjMMJ1FCYdJ35II=,tag:gAKChcouJo4qoTSiR4pBVQ==,type:str]
    namespace: ENC[AES256_GCM,data:/GCkJffT7vZk,iv:qcQBMFsVGvt4d7plQc1Pr4v5B+TI+pPOBeIMmLVCsLQ=,tag:i3V2cDt6mKsjgeaLZhH1Ng==,type:str]
type: ENC[AES256_GCM,data:EnSvTS5c,iv:aKLexOdiL6pHMdjmiCtgGOnIh5bpvclkzQiO4ht6lL0=,tag:sfv49oAnpXoNcigeluiIoA==,type:str]
stringData:
    private_key: ENC[AES256_GCM,data:NNOq+JAfdBGatp55Fd1eNjkGS4FuIIsbDaP21/3y4AYh/s+XtUcZ6VsUNr/LLUtsDM1LOybtJ27XYU6U2Amtxg==,iv:E8wPlQurUBgPbQ5b4P8w6cPMd6ERQ0XvzpCBVoEZwtg=,tag:F2W0/t5nZnEVPWXtU+Mvbw==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bjJUTmpYTHpEZWNXbnQy
            ZHhjSWcxQkRva3JjMEUxUDBIbUVudXYwNTBNClBUbENnMnVZRWJVQTZXbW5nNHM0
            YUNNc0Q0MEE3cUI1SkNXL08vR2pwcEEKLS0tIC8yaXVmT3hsMHQ4eHVzTHk5U2p5
            UUROWFJyWk05WHM5QVNNY1M2RTI3VUkK38bJsoQjxIWGd0O/N49aencdUwRoQnHE
            5Jd47zffQVkmTex1WR2PIN2raCI7JZWtU54wD1ZdmEWjbDKHH2Rt2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T15:16:47Z"
    mac: ENC[AES256_GCM,data:Z6pcP7AvTu6FcNAWIKc8dsMUWea3mXt+UwXTZ9IKnC1avvH9p93ql7rJ0vTB+tw1unsJ4c4zhasGTday31FTk8lYh/Wetrpz9eN7W+UNKNDMkjsqewv301dqxA1OmfoKEEyC0F2Lt1M/sgf+3e3x3+kVi8et1dQ3C7YD/dT9t9E=,iv:duQWv++ORfZws1lGJDwafNQ7jCoOrI+k4T9TKmO6+vo=,tag:h0PDj6Ea2PbWliUC8KYsng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
