apiVersion: ENC[AES256_GCM,data:iRI=,iv:I6Gk5+srllNuuUvUWLAWxAN0J16yBNX/LtakkoQxKjM=,tag:Tzh3eXwRlG8FfnomN7Ldyg==,type:str]
kind: ENC[AES256_GCM,data:ScC/+fl2,iv:lHIJjW01/l8Ltc4yHT+Ix66b/qP6txVK4r/lMRRHBu8=,tag:cGCbWbFVGJeLHKp66KVjww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/L2N9/dwstoakQ==,iv:OdSUdtPySTwy2/Y/k0fJJbf3Lgfg0GBONRkjHK1USXc=,tag:TzEV5qabPiQIuK4yGK6b5w==,type:str]
    namespace: ENC[AES256_GCM,data:ylAP,iv:d8yz5PEcV1IvBQEqLiNL7igYTsqlvCyo8qyCNadYLm4=,tag:xH3+RzcD3EVE14IXBQcYkg==,type:str]
type: ENC[AES256_GCM,data:h3qJoVwI,iv:Zptp5C/jbUBBVyHdeA1OdTU4ObVoJfyWGzCc+ZFiMuA=,tag:19Q/4YlsU0Kv7mbXOnLRYQ==,type:str]
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:gwPvGkr/bQafZrwRSCZGMQLIrVqrgpML3LnxqCQTfl0=,iv:cOrEqa+rbjq/f42OB5AABSn77E5z5Jjc4+hYfDEMe0g=,tag:3ZaXduaPAGcSCzLmaCoKDA==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:62QXj2svcQl0BXA7NGNYK/Lv78hCQR+apJ5un9sAlm6sW9Bw2lZ3irBMI32DN62M+b9uMLMPJA5YmHgT5mIqiA==,iv:Shge+UlvIRHSPoMwkRNqxErP7XjsAJxpLHRYvTKc7TM=,tag:bQBVrnr4ASE/Gi5FJG4/yw==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUEFBMnJSaVVkc0xwdHBx
            ZzM5MklZUEQ3eTZjb0VSSjBqcEJuR3FFS0hRCjc5Z2FnMDZuMzZ6ZGdqRkkyVnUw
            cTRud0FjWXdUVWF1Sk5Ba2VsUU9lRU0KLS0tIHdKVTJlTDNlR1NzUlRMTkcwZGw2
            M3Y2bStaY3BmcmZLR3V2eDEvekExbVkKse1huZYkE/4jEUBIF/unSi1WwtKK/4eq
            69TqocHeTEBhn2JJZXstn4AoffM8Oh8Rhde6rLEnrqdAE/Xkil3vPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T22:02:49Z"
    mac: ENC[AES256_GCM,data:jEIJRfKqcS9nAHlX1bIOdyv0lPHgwAkmz48Ti7N2/GgQDYU8P+cW//nVQN9liZx+1c0Lwd0be9ezwixB74tixmtWAi5AN/Q+49gFycWrzYh4UfStNTiu7+FMhrDKDps2QQAxgRuf1vmArHiSyckNwllXTxosOpHrA+rkuZd0KUg=,iv:NetW/5M4eGhLoE51rTGR/1+qECDZhGdBlrcIdq1YbEk=,tag:kQkhgOq8n7c0C1p6KcukiQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
