apiVersion: ENC[AES256_GCM,data:pfw=,iv:ktbJdlw97RM2mtKXU8j8VdzqH+Yu4BNNfqLqsbx0axM=,tag:XBWMcTEwW2ZNuyFbjs5Kkg==,type:str]
kind: ENC[AES256_GCM,data:B15GWuIC,iv:IJchaNJ/bV+b6VU5qJ1I/M3ojKiMIIgsIyGi+EFKdIc=,tag:APd2ELeY9YqyNGVj3I1HhA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:obbrQhme6PI+ncyH8oU=,iv:KzM0BpYyF0E/4Mpu3dAAkDc5L1k3w9eZtW3hfKNblx0=,tag:/zkicg7bdkiXXa0Y2Ekakw==,type:str]
    namespace: ENC[AES256_GCM,data:2hN2ONKVwPs=,iv:d4aJcq896DjbZlQR+k62pgyrkddaLvImzzC2lEYi97M=,tag:2odIJM2ZULlG1/61sqTZ1w==,type:str]
type: ENC[AES256_GCM,data:rzZPje8W,iv:tszcMFSEfTHF5BFOIfO0s9rw/SrmObLRUeJWHu2JR24=,tag:rAziZ25wrj8VoUYxc7gzrQ==,type:str]
data:
    users.yaml: ENC[AES256_GCM,data:aqMugLZ7b6DyAb7WQjJfkTD15QnKVBeu0qI85pfu9wS3DRyjeVi8dwmBqQwodxnQpBD5RyLSWIzjusinFkz0WVmEXoupWxKzQgvqXETHDOfEF5grMSwi3XTZUQ2t4YCISxrxCi+YiPQxenJFfQF79v8OBP+U1iOPN6Ros+Ab5qcpPPid3+y2irTLfxR8+8rLfEyjaDG68nUGulzJ0wcoSp4BQ5g4fD6YB6EQUy3cZS77dQTLsyINR/nh+qDRM8d20giTFWeZKo/+/I30NEjysZNULaYU2IiA/qzJQS0kxu/e0nmhD6r8QuDR5PlXw6jVXxRhXkSKD9UETp/g0Vqx5q6oIQ+HB/htAgzJOgheLXjpSMZTXQ6BmmKmRl8nYlS4rjC592Yo2zav/vkTmWKB1XlIuv9b5BNY6aedIxjlvO7kE08BHkYPwSE4lwCOFMWNXImH7naKbo4=,iv:P60knId1lZh3tjxbi7JbtdjcvsDbJEbR6glk4HcoA8g=,tag:bfzYyMJs19dWH9tAiamoNw==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxS1oyU0NKQTBBZXdGZS9C
            TnVuMjI5NGhhb2JhWnprYkVZZyswRlBmQVdnCm5KOW5XUkF0dVdCblc0MkRPV3dF
            RGtiWENMaExGZ2hTSEVkb3VPNEhxL00KLS0tIEdjSlhBSGNqS0lZRzB2cHRBSXpO
            WnhFZTRyOHorZExmVXRMaEJoeTNkakUK3wYwOO/bIm9qd0LWpXw9cme0oh6DQ9Uj
            6QPbcoqUcHRnRmEC7phLR7rEmtn7KcNEfcXG6F8OPBRlsu8FkY5xVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T03:35:51Z"
    mac: ENC[AES256_GCM,data:RBQ6HFcXnMdOuDgVdR/5cYblA/8g1WI86hesTWLN8Co1+uS13Jej/d+/43DgfP0y/a+J/yjxw6PznxQ3XRV8RtNNwI9sOKQPXlrr1iOtfv7b1I3bQyTy4m60y2YA0Kru9tw03C04bWsxe0zxbIf22ktXtjQ+XpCJgRezXtyZmJo=,iv:8VB0dzwa6IkyT7Do8eQkSDYy1Ow3W2uOedaAe6cEDXw=,tag:loGN3yWZ35jtkmJeI/wkhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
