apiVersion: ENC[AES256_GCM,data:OFs=,iv:3UG1ApKF9FqnPdT5Y34Ffykde0tPwBHRr0bsnG05oZ8=,tag:2iQ8hapTtFIi8MhvDNe+qg==,type:str]
kind: ENC[AES256_GCM,data:awGJypWA,iv:hXpsHZXBDR8EZOGA4DOJoZ+kc3adKmi4QNqaQ63DRt8=,tag:UGbQLcGC7rbJfXwvr0Nx5Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ou2bhHlj4sRkDi0F+lU=,iv:4qhzINufmz+wllbVXT5cOA0mOSHYmJfKK2BVcex2KJc=,tag:nu+gL0r/WuIwGPfH5Se5UQ==,type:str]
    namespace: ENC[AES256_GCM,data:J+TyMpfadWM=,iv:LDjwYoIvxwEkrZ8m3FY+Q/N8sqoAKd2wNkiBjNCEfVg=,tag:4fMQXYFkJGuyPdx0jIXL2g==,type:str]
type: ENC[AES256_GCM,data:RIabr85E,iv:7H+C1pZYzdqqLjCPZLDhYCfD1sjxOqBKo1zejb4eDxc=,tag:9t9A6rYO4qfrKr1S6yCR6w==,type:str]
data:
    users.yaml: ENC[AES256_GCM,data:65JKUj0z0PErg+nsPDDCD+NHq//6J3Dv91OkxbkBSY4/LyRM8TP1xbe5E/VRH/FLsIvT1HqTRmELt9dNDn3E7FJJk5up4F1LGQ0b/LqaNsx9RDCXgph75fqE75Jgo/DRCo4ZONMqPYTHGuXmStbwfYTdV/TmV2Heo5jYGJDLQI4XJ2HyhP11satvsTlKA97Dols8kbcHWMfeZEcRQmLCK5NMCTSo87AwJdVVgAD2b9bI8wht4+SlTWNt+21OtnAAhXf99lWiC2EeFaq2gx96JT3N6SLulLiyxbtWFsN0alcd/a6Cixym5TSXaFORL6KZim+ldMrxrtHGp+1H7FS4PT+KwlYdsTzoa6QJeEF21TnYhca7eiu7aZTodMNy8+e1pfeB78l5tK27Plgr7iTI8L+Gp5bJ6TDyaOHxVJJv/FzXsNJaWihEoWapqJH3aAG4,iv:GLV0dDY5JsX9DfL//P/Z/cqMYp2EYTsAXcP1skBWLhM=,tag:wcHsP4C2S6aQcJiXZ9oG1w==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVld3NUs3dzV4TDNZdVBO
            RlpjaUYwZlBsa0o4VjdoL1ZjeDJ2TjhGUlVZCk95SmtpL1lQU1BWckRYY0h5SFZj
            L0lQYUwrbUVaVytRbnFVV2k1T1BqRGsKLS0tIFJrWW1ZbzMxaWhHU015STUyWCtC
            Q2tDSEJISGxVY3JOeTlvNjdzNXVTOWcKz06mE5NE2Q1XEpWwW+APZPzek+/rvlVg
            Iu0+DvIKTjYcP/icOH5MeUOFmfdXRccnJo0dhYtJNbc/Yk2gjc8ULw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T03:44:01Z"
    mac: ENC[AES256_GCM,data:DNAYDY18IyposPK72w6TaOkytk5UkjnRX8Po90r2TySsnm0KW0c9O4X7t2gfNG8eXuRz5Ie87YxMb63pM0PDChTwRXQMpqCSOsydtA4IiKnZ6y7f1sM5ikgHlGGVmIVfQBcdF6KhydO6RttLc78S7v53sdZ1jL10EBCGWhQs8bU=,iv:AwUf/y35r1rS54Sum40DWIVT6QxQQXLX3EjrfJ2W7rU=,tag:BeKa9shDdbx8uPyMR39T3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
