apiVersion: ENC[AES256_GCM,data:uMs=,iv:JTZcSlgSh8Je13zzDlGhzkbda9QRN65ihvfjzebRrGY=,tag:nMWEo2GCslPfXZJcJeSe8Q==,type:str]
kind: ENC[AES256_GCM,data:OTCi8E+h,iv:PKs5+OxPqwfndptkFmTPXcoNepafD/mP65Hbuhnmukg=,tag:Uyu69PgTY2gizSRGCnVMUg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XRq6D6OzGGZtBJ1UyGU=,iv:gwO5A4nBnfuOVj1w4D62yRNIV5KJTHG6Vtu2w7h5ca0=,tag:p8p/EIyAB6fIzgtcGcy4uQ==,type:str]
    namespace: ENC[AES256_GCM,data:7n+DTTE=,iv:qK15KSpB2M0OzTOeK9U1rBF14IMmIt2K6CWbhe/0fCY=,tag:sy9GnSr0Db0UG2cX4lFi2A==,type:str]
type: ENC[AES256_GCM,data:TjHwxQMs,iv:9f+EwYoju4VuHZP7vqNfjf2Yts4kdDGue3TKwbWOpeY=,tag:bRgx1z8ZlomDhE0GFNqT0w==,type:str]
stringData:
    bot-token: ENC[AES256_GCM,data:vrQsbxx+giwu2BltO1sQPPbdvNcGf6mxtdj2ufLJmYh4GH3K+TJzlhyZZlIgLQ==,iv:N6Ys/UKbOumMLebel9uuHwfvlTElSLH7/NTTVwr3NhQ=,tag:cDIm3i830g6ph96QJa2k6w==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSVVMYUswdnZ5bnFua3c1
            NXpVZ1FndndCdTFseThraGhjQ1BncTJvR0Q4ClkzR3JmTEhxY09QMFh1N3BvT0Nj
            UkVlNW9NK2k5L09iVmtiRkxyaTZiVGsKLS0tIHh3RU5ZVnhBU1VrTFlvZ3lNT2ty
            YXZJd1dlZjhrM0hsUWRSbEY0eG9mRG8KAaG/3+fwFHy9eOrmxfBJ8mGOtfLwvtdS
            6ANbZHNHjJ5W0+gKJ7lR3LFofNEh5EfSeBYyR8NpVtSHAVEzofLjcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T07:49:22Z"
    mac: ENC[AES256_GCM,data:YYPzYawhxpLBoBpMIghVRIzfX6fNlJkLKemR2d2PvdGt/sXxaj+ohAKDx56FJciF8asmFHiZjHF4BNikqqQWDK5V5gySpNP+lEC70uDkpcI4/zQKpTwfPadKS8yJC481Aka+G+1uDO0qcwfLUYOzztj51xXI1wGz+Aquzy4quzk=,iv:KT0H7UKpGqRJSjHXwCvro/K0HHWnXbn1bzvk9PZ2XDE=,tag:XUa6nMUiPVDVZFAxo1gLSg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
