apiVersion: ENC[AES256_GCM,data:yE0=,iv:UCRUGQNQfiek75c4SZP7Mnn7nb11okboYair7WYJkbc=,tag:/db3wh0+5hLMOAOs92y+jA==,type:str]
kind: ENC[AES256_GCM,data:Qoxy8egc,iv:rZi7OErc5FrWZmd3IsFRwD2YVItG+JXYK5cctoKEFxA=,tag:/G/fVJjweyvpv4ekApaWbQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:masKZCkPLOwXMX88XIfGPw==,iv:FXsp9WXztF6EPA8A5bmwz4eTQBkGBA6z/u0V4cIjBWE=,tag:rNkLEX6sPoLqDpAyxcWfKg==,type:str]
    namespace: ENC[AES256_GCM,data:CPXhPi0MTmaI,iv:aKddugiuBIGsoEVEmqP3xF6RzFoKXNlcnnbfBwrRaMI=,tag:zz831lG2MdVXH/ZIST1QNw==,type:str]
type: ENC[AES256_GCM,data:4k1ootdQ,iv:X/bMHHhhGlUlGt6VPZkqrXxsKrTs/2qoEDTc6BHN/Lc=,tag:R1ZMjdYdqgpIoYMJ5JrNeQ==,type:str]
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:ecX/vav+pssakjvZbsatIBv/CTnyX1LUE77gC8rv+XA=,iv:yd7TAXQCCQFVfzs6I3gRj+32S1ywH5KfEkneRWMhXeo=,tag:naDBTriXqiNTKhz0PXhnWA==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:yCwR60E5PLkidLZoVRxXgMrH1cyqtvY4vym3sOjoedL/i4C0sKTv0RUXvfVmLQjz2ZzCI2DLInYd4odtuLGrdQ==,iv:PFwhqAq3CnEri9kU4B/C0HKAOUsYVFCqu1MHl9cTpHY=,tag:gs91nmFt6BBKmuNQG70I9g==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:wdIZNEzGEh91ozdn,iv:NxcMjJQ42x3nN2KWq/kI63/513r8AVvlj8WBhlfivDY=,tag:q45HIUXg46zLi2Do2pfoxQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:bnSIHPeaWaPImpXU2FqQylJMMe18fu5DdcQud+6SdkcK+iPptpXgDkX7XKg=,iv:idcplGy2IFx+9lsTwc3rQT90PdA9jbHF/u8aqcp5WwI=,tag:z/fjEmtq5LGCLg/hgq+qVQ==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:olUpx9Nqz4/qB5SYHpdR/fXDH+nVfEIsh28lzxcini2Ivjg+y15/pZ1WrqW4mv6+DT8df1z6LjyX4YmKzZlxtMf9WeK9/sPiMTquUCxt9mC1Kd5teBKDpJNI08forcXu6VaZCajxqIvr8OG/mfz9PQiwry0Zn0UA2pDhBNI/7qR2o2mh0BwNiKBlhLck71meu6R7iHufdwEl0pG2HC5j1l2S3AOK/4Jy9qTfbRI8HTVX/0fhnjNOB1T8miex6aNcIPgoiz4R9dbjKG/GG2LudZCkROs4QioetYkpzhy5xmCe3l8kpR1DfNsDqaxA4uZe7wrDa9kf5Gkcd0KMeIzRvRRC7e4Df321JMS8Bh/inKFf2Up2hofHM6w9YE+y39xce4MY5EICDpqikPmCASOYQX1pbUCWvTIW3DwYPUnHWTZ9LZCROL/PO5rXRrVFnf1+pA==,iv:oHc4fCUW+O53ox073T4hRkZv0UZlahD5C/fRTTfphrk=,tag:xAcS+YVUVIEsLiP7DBTfNw==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbWhzYTNPVmlFUGpia0xV
            ZnF2ZEp3bW1jWGtaZEwxU0JrM1RwaFBQN3hFCjdyS3htd1pOa0RDREJlcjBoVWlG
            WHlkMkZ5LytxY0d3VDh5ODN6Y3NFWG8KLS0tIFB0dFBnZ2RNeUlJL2dkMjltYTJP
            QW5PSlhqWWxhZk54ditNVFNlSVUyVVkKKodK5xxt01tX3CCe20kbBlkj75h+08EC
            6qpgd+ZYhaml47kydd7ezbai/QK0nMKAO8veGtTNId07yRZV9m8VQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T00:12:26Z"
    mac: ENC[AES256_GCM,data:qXdRAMWm9Eze2i6azlOValk/SV8XEc1Zj4mnfolWx3sa88OEu/WOKT3S0j8L+D6gOh+SCDgoSj/FiAyUGP+XJNez0ZikCkH8TNntvNiSQviPgxIXc0SgliBSYnHK2Vzw5YYVYUqf88zPYBcFnIt12inoiR0VCnG7Yd7WXQZWNmo=,iv:IIZ4QuTjTCCLoIFpb0PypFW7DpE6hz5PKRhz2aFu940=,tag:21biTSOCuZlJdiksEgiCGA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
