apiVersion: ENC[AES256_GCM,data:2cg=,iv:iz3runwIPSvB079YLhqtb4OnDNLS+oL8G7hEkWjkT2E=,tag:TFHA6QuoywxVjrh7YbJjvw==,type:str]
kind: ENC[AES256_GCM,data:/nzhEsVl,iv:Y+Dbvz4tN9NYHMqeOnn2ggmVPFl3P7Y73H8kmLsWq1w=,tag:IMfpHjv/2oeNeuAiDDErTQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/hCMQM5JE7BRVcMj8eh1ow==,iv:UkOClDKdjU/PrlRJfqqBjvEzR4jzzzuGzUF1Lu6LwTI=,tag:2cUufpzeJu5s+lOO6ry6UQ==,type:str]
    namespace: ENC[AES256_GCM,data:5XhFVwzeKkSQ,iv:Z8m+7UG1iG7UKmUajZIF8OzJBCXXP3So18H6CDXio4c=,tag:PiAFLm0c0uf+aVDn/tcmUw==,type:str]
type: ENC[AES256_GCM,data:Ri2Lo5tb,iv:12M8jQZp7bz/9cZDDhX4xMTcuTmoUKwrekUMgbTkxaQ=,tag:+xlSMaqhvCyhUAiXaDXBCg==,type:str]
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:Y8NXRYtplxtmpFP4QFuXzsVux6flwFsbdyykhuJXV10=,iv:C3KY2JqvLSMPIM+9gGKBeImm0qUStp0btX0J5PJsX94=,tag:MXZoP5o2F3K6HuTfU2Rz2g==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:3OYpvZpZ0SuseyyrkiMc+6vPNUapfhc9+l3ATDq6oumkLMiIkr8CqfrRhH+P98EZqmDr7gwrwVGyFPx5dSQlGQ==,iv:xWy0kuHhAPMQiBTafBdkgFHAp7F4zkuPtH5e4bgGa70=,tag:57TcflRuyVQM3IBRDEa31A==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:FT4/kqA5epBtmWYK,iv:hILML18JPF82+hu6WAnOTvrFHPYpMKAM3FhxOAePYyI=,tag:PFuxrxIn7iMOR+HMCI3QEg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:0McSvo0lfI0OjNyFO3cMgZ2Y4ci7oRqJoDIQGgj8IvuH1XptEBGkWnRDWio=,iv:a33cXqZ6wWbxN5zpT7wIK/PkjZ58M2dvyYQCfdv2KVo=,tag:rWPRZScoV/QpcJhyI+Wh4Q==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:kMWV/H6Vanr6FM46+POFWZr4uPLQKR4wNSmLV3i7i5ajMTQ4vINot04HrrEkntRdm1+AXk9M3DGjXgauGwyvXIlSOPl8AU0fGAyugrXk/AD2dR+MMrOuYsQ37S2M6ZwTxb2QhF7FFaI+IAnn2J5rq/Fo589a+oglynMx3Z0VTHDDsWyJ+FNlllS4pU1LhHzRbJKzDwLsd07DkBhzNgUts57QoKDjCrJapVg4nnacJ0icQOLpJXfxEwv/HzrRgjL0tdeJn5zOCexUvWczi4f6c8Nv80e7AN0Oo64u7TcHEvVz3KgoCXMgknyf5h4WepxQ9qv/AutXocRNtUu2kEkP7cMHaN31UvQ0lmAcJsQSnU5EYdDcI3nPhbqBOPi9NQnqZbwpLsy8dGQE4mZakuyXm4tBQKJiAaK9SKsRFgJzDfSBIxxvYdWdtY7p0sGMD/dxtg==,iv:KI1n/IQpeSIGvtb/jMvemKbymn+8ogzfkbilh6sJ0Is=,tag:lLa91BH0Weyil7q0Xe8hYw==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdm9IVUt5bFR3Wk0rYllt
            MVN2UjhCWTFWRmo4WDlCTEZsVmt1cExHaTNNCndiS3R0bXU0MkVaTFlRek03UWc2
            YXlLd2F3TkZXRnM1NVN5VGRwSEM3UDgKLS0tIGt3T1doenBUVUVIcTJTeXoraWlC
            QUIveVBDMkxXOWJFdU5TRm9UeEgxUk0K1obdzeNL2eiyBuGYDm1d88PiOeeAQWdk
            RBKd07k/cI+bBuA9/Kfvc3d6H7Gr2p5j4kyG/Y5e+EpLcJ6mOqd3sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T08:45:29Z"
    mac: ENC[AES256_GCM,data:3SK8/WHoLjuQYptu/VVYdvh9SDvbnRuPN5KuhxHspIvxj4OZx5U0mDjMi9J5Yclq6A0dDGFXZV2Flvj90vEfp5ftTQuhWW6zBGvNloRUnMofVd/FJppphRq+UwgmCEtLpbSiORGzA1am6ds4clmYfcfXFbBr24QnMBTp1HiC2AM=,iv:7zK4tM5gCdFL54/xnUQcOjDHVH5Mvbkzqc215pirKoc=,tag:TG8O6N7PetAPOQhoO3Vteg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
