apiVersion: ENC[AES256_GCM,data:O00=,iv:t/kvjQmAVkVSVEFg89J8Jyu1LbRQ9UCoXY9vxuKfb/Y=,tag:3HCk1nVrdnax4O9/3aYxBg==,type:str]
kind: ENC[AES256_GCM,data:5SN/Tc0b,iv:dnlBDM9nIrW4aCsmwTq+QmYWKGQLxxNNJdgaXpeuvDU=,tag:tSBfeMr5UF6VKfXTA9TILg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W5Powt3Nyl+b0pLrzAA=,iv:nDSAU8St6fvnmxcTTbF8mY1lXJXc5UnAMkHv5OeHLnU=,tag:+Suf3girdktn1f7+TTvlSQ==,type:str]
    namespace: ENC[AES256_GCM,data:731ZxzNJ0p2d,iv:95d9i3Vd2KIX9/rtOSXHYKFo3EdXEFedmDmQTNgPwpI=,tag:VDf/OeCLaI+O7aJpBBy4Pw==,type:str]
type: ENC[AES256_GCM,data:pzqGmJEL,iv:/WiRzLdjA068Bw4ObIeiG+giz5nO3JSBp2j1vbvzvac=,tag:ogpYdWrkhJQ6GXx6YTF3Iw==,type:str]
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:jLJF52fOXRKw6v7gEqOWhB5wdsEtZeK/JDiIVtNMA4XvxBsISbgtFgBfXUcO1o69,iv:WZWIlsVFr6fLBOn+6jEigqDxK5/lpjPj2GI8mX16LNM=,tag:dYCKEz04IX5iOa9mPQgkpg==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3amhlb0s2UUFsaTkwdjdQ
            S2hVQ1k3Ums0aU9DaFphRU94ZVBhRDUrTWxBCm9LTzk5ckZsZnBSbm5JeWp4U2tY
            SXFuQkp5S3drUVdvU3FYNGUwTk5mOE0KLS0tIC9VMlRUQTNTT2JIalZyNFhHbmpH
            VUwrSm1JNUlhbjJ4VVlIcCs5ZWluNVkKed/s3WCd0sr0x9OboMhMFq4N9/bBPxlS
            WuatrshyNc8bu76eP2nCZW1/SCw9Y91WWrKxleclGzifpVdrt+wIng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T20:11:01Z"
    mac: ENC[AES256_GCM,data:HnS8EbvBGlWmGjAAfC2dc4D5/l/4D5fvdlq8oH2LlXQtBFFPJX+B6+J/UrIOtagwgqWCAvcrUrX+kzkawr18CAw9Iiee03zad17mQ1RkbQCaCoz3L8itukavktCMARRRDR5uWwk+7LNk/Oqq/HBpzqYntKPL98BCTXygseH4ZMY=,iv:cQMc4omOLl3BC9lpMiPYmDT//CAiVsR9iRXxhXA8bA4=,tag:t+Y2CHwxPve2NGEFZnQKIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
