apiVersion: ENC[AES256_GCM,data:99o=,iv:6rgZgA8ViqqB0/iIJoBO9PD/0tXswIoKSyOxtlTfVgY=,tag:k533VSzUjJETVg0miB5sdA==,type:str]
kind: ENC[AES256_GCM,data:L6oO87Lf,iv:EZKlt38YFeMIqwFQMZpE2AuqDLUVZZOyNPT0z0ZZkzE=,tag:StProwEhbpRR02gcqS5R0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EUZClcpBAgiwdL6nNhk=,iv:zN2Zlo8V6ksOqU19r5Gdn7h1AE+exF7g1DfLAfPJk6A=,tag:JdHt2JFnAE7mUlLBFHFy1g==,type:str]
    namespace: ENC[AES256_GCM,data:fiz4KZk6ebd6,iv:KSOFhoLMm6YwSJP6sKLDAaaBDNn7HRH4DkDAUPi4xAc=,tag:Zk+iANpbqarthE1ArH/HGQ==,type:str]
type: ENC[AES256_GCM,data:mdx0eBt0,iv:WALnJmOwV8e3nYpjAsej3i7/h0mti0Xb5Bv85g6A6UA=,tag:IsKaBrIWN+9tqX1uHS65Mg==,type:str]
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:x+Q1zjr/6prIQxqVvvwcvfjL6CwISuyjzUgXGWkBYIYRRARN0fJ89/MeaGuwjpn8KEeqlvfmOO6189KFGw==,iv:nE2C8mUHdQroscuK5SNVOhl5B1TKJNBHKEVMsjOQMOQ=,tag:SmRpkWA8LjbHHRI+sZgLbA==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S2Fnc1ZDZE04QWtaZm5x
            TXc2cHM3OGFUeldDV2kyaFRaME53dXhHd0JZCktmajZrNk54N1lWUWc4eVBaMXFW
            NFBtNGQ2bmVVYWtqdTNNOUxVVEtVQTAKLS0tIFFtK2xTTzZHaGtaRmowMklScjhr
            QjhaWDU0RWZTQUovWllpbEJaeWJlVVUKUmNA0dl7x291a9b/zwyRE8pLTffx9q1U
            3CgiEPrUUDYQ+/FPFnNhqA9eVXu1s/3Xg9/S/1ugEAsuNiAmBto+BQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T16:34:11Z"
    mac: ENC[AES256_GCM,data:82xxsOARSwpXGPbhjOcDYD/7F9HGm9q+ZZycRksy6ugRSy/STuzm0ZmcgqVm9pH/rxTkI6HmL/X808+fES11xMutUync3d3G70jZeLC3olg+4PSaj3JhgmMKFlfGfogaOkR9SJ3xIPtX2VWNEnplb2YU9hwJuHCsG1MsjJM8AVY=,iv:v5Nr4pAOkeFHZ2SHQB28XNZ/hMW58yMZA5RgkgE92ro=,tag:j78Fv1lcINxBE0zV61DrAA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
