apiVersion: ENC[AES256_GCM,data:7yI=,iv:leow8gyK5c/JvdredT3RpvPbNQv7bL6bmSB9hSlniY8=,tag:p8ZDRre89U8XO88mZ1QIvw==,type:str]
kind: ENC[AES256_GCM,data:N62Eyn5i,iv:WqOlm6Y4IlB6rsSDc2+8foEpk/p74pARj9nkQZd5Soo=,tag:1+6552PGdTTrUPObLbWcWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6Bb+nNGFsBs1J3ZhVWU=,iv:FLluVIBSBneWMFzLuRujaKpFpXqT/Xw2hYD9hN2op28=,tag:/9ylZRpeYfJ4f1aWr0nGTQ==,type:str]
    namespace: ENC[AES256_GCM,data:+hZgNx+H7PG/,iv:DZ2z80TKfFNL4CDKuxMhax3e5L180/aGasNk2V0sdZ0=,tag:tqa/kJX0fjm3XbGq2fdWwQ==,type:str]
type: ENC[AES256_GCM,data:xz0fgC9+,iv:ZiBfykyAG/uGx5PJReLQdBvFXRbjQkpukAcGMPp8i5g=,tag:9ONqzwYMj7gYQbs46qY37w==,type:str]
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:zmUTEF6IGntFb5Luyy57VJEKXXrIw3hw2XjNtnXB29XlnuDk5pLRFIZMPW+PO0J7xHL1V31KvsWy5gGeFKk=,iv:lSsIfwoKWNWX6W/pBkY/6Ywu2VXdQ9UfIl+H7SgeF2s=,tag:ypPx31/KBzuUycuH++MRqA==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucHMxSHVQQzRYV1VoMEpS
            R0hzdkxtUlhjRGZiK3g4bUxkRW1RVDFhcFZVCkJIdDdaYkRlZ1d1a1JzekpzRXNy
            bGpGejhLbE1qQjZ6eHQ2anNSdUxQUGMKLS0tIEpJUmN2VXhuVkZmekJUc3FFclI3
            dnJiZTlLZjR1WGtqc2VHcmQzbTlPMk0KyfYVB6TPzI83hh43fDI3vwaIspJ3DOY6
            gA5HEWXMdOU3MAc+wiVC14zmwxxVd+jjxnV4KEk4ATQctJv+FGGNXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T17:08:22Z"
    mac: ENC[AES256_GCM,data:YmlrYBVov4YiFPZEPYkz5CyCLfYl65b+IxDecz54f+CHC0roFJXO36mXPuldPMTe8Rn2IZTGLWHOHHvDU6KOm6U1Z94PgaiLKkOBbFy+/W1WdCKLVOzm1aDp2hKnv1Om2OF4uXMA2PWYw0RZdChHRfbS50IbK0RtvWCmpJ/Hem0=,iv:M9BD7gZ3twHj8hzBUlK0z1m2Alcrm9QfI4RBK83BO0s=,tag:9yTKkZurM/Lw44UB1sMqTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
