apiVersion: ENC[AES256_GCM,data:+yA=,iv:57MnHzPtFkPr3ST7/QaYSzN3jh7qL/Q0rzy6ySmi4Hw=,tag:ORhdHrGiJrWZHyai/YEKAw==,type:str]
kind: ENC[AES256_GCM,data:SD31bGO9,iv:5SyQq0AkmUbOFysQDznxmWM60WukBKirGj4PxI+nmxU=,tag:DB7bpGsiVa4qRYik+MjNAQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DEofIS8liYioPQsHqmqOlefKg+ej,iv:Te4DSjKZ+c0P2SMpjqLPZnOIwIMas0uBVoBhzlSb7No=,tag:1Q2hHKVxRIYbBqWRMvCQkg==,type:str]
    namespace: ENC[AES256_GCM,data:5H20siFm+A==,iv:ZYxqyuU9cv4UMC0Grrj8Wh0nD4qjR/TXl3sC9JaDQJU=,tag:qzJIN4QYINoNREUOVtZ5Sw==,type:str]
type: ENC[AES256_GCM,data:F57GYB9M,iv:IscsasluuZTCm0VTryb9nOOzYCozOwRIBBAQT0KRINg=,tag:W1wE2PaYOW2cYovUfq1X7w==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:P5IXPqdyzanq8dH2HdljiT1Vtttv1up24g==,iv:S6JJtzJ63TxSLuwm6djFnZum/Yc0uboWUqYxeu2uOMA=,tag:ic9Vk+QtJ78/wtVwwqKAgA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/FB4PXCfrixh2TDkLXKm2Wj8ZCmFBlHf5vGsfNMEUg==,iv:il/uHMTPYjfNFXh/dxNAvxisQ6dACE5VhyXL5iNrfCw=,tag:qN7ucAYAgv0NaQx3Sj3w/w==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:nvkuBjgkYAHv0VOnNsEsn+cUoYSG+lSvKzfkLCFbbhf8ZTpNUQXV2gjhLK7D0xKWOzKkAUbraUsRsyW5bkOJXpfazFIWj44Y,iv:u+vGgMBJWnf76W55Tta/xbyoJkej2pP+q/termbFOYw=,tag:ZClEv37V5x/sVw06pNC8gw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:b4XiPACXlLmQqgjxsQzOAyi5FvLWAnsp4/y/FNEA2SI2xi+niDEEyye592A=,iv:7+Y+3rJeGfgbB9R9/qKiChGHwhpck2Jeo5wG6L7B0kU=,tag:eoeY0hSn+C8bTMPjrraHYQ==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJekpnN1lQa0ErWTV4NmUr
            RVhhb3FBYk1TS2V5VjJua3VBYUVYYS94a2g0ClZ2V2t3eEgrR3JOQUZqWmdZLzU5
            eUNCN3g1RzRJOVg3ZmVPQit6T1Q5Z2MKLS0tIEl6MTVXanNxRHAwazBvNzZUb1da
            Y3pJdGpjRTdYaW04WkczdWhRRGRXZ28KVpB7tweiz0JwXVsq4qCkvl/WZFeOSNX6
            KhzVmnJCg2XjVGmEQDkk0Hf7AVFSqracqdDpTpgPaiNQmjWVKKYG4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T08:14:55Z"
    mac: ENC[AES256_GCM,data:FYhf1YNb6sBl6LjKkUugOeyhwUTSqsmCLMTiqCwfa9T7E3ettlN7eX9J1E6nmXUsnKwr8of6O4rPF0m2OeTCYk7OMUcZWeASeiHvgnQLu5O3cucgYC/lhBknDr8S189S63IE1lL5GGjPBGejl8w2ufzWStdJsV2w5Cwc9UiWq2o=,iv:62sQVMd1uoRluxY0oMVG93zskQJPF6UdBrBH3CzJJWs=,tag:iete2Cosz0omiMyZjJjcXg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
