apiVersion: ENC[AES256_GCM,data:0cE=,iv:46214qYjY6pX4EDtjXB/CgqA3YWsEJMzKcUZwanK23Y=,tag:hkfm3WgR2t8+ie/ndd6VFQ==,type:str]
kind: ENC[AES256_GCM,data:lGbwzjJz,iv:nfhuH4/iKNrm0FJXr/yKpwMa7txQbhKOKWbgbnvrJJQ=,tag:xTskMziNsXBX8J14wZGCBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dQ5km0OHOmCcN/jyJpQ=,iv:LZj4vq5AKSMOCIh/flPuQjimt1/eRCuHgNI71BmNO4o=,tag:kAVem5s/GlNF15X8/LDUFQ==,type:str]
    namespace: ENC[AES256_GCM,data:k//KcbIMpw==,iv:uneP72j/YyiscbEpmBzpRJyogEeglCmX98QlpTphtcM=,tag:qVUmOg0jfqoHzOsyHd3/lA==,type:str]
type: ENC[AES256_GCM,data:fO9bDABm,iv:U716YSZrYyYKohqFkU43BoKBogbtl8J/vSB/qU/nPEA=,tag:AJSjTVbobTHLHm7hllbC/w==,type:str]
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:uKCsuMBveMzOyYRiqMVOXN1j6pYYbHIFLQWD0mZD0HO1gfFpKXvDZc4oSaI=,iv:nWvae8Po6tXukqGy/LNvbZh/Qv/nK8Uwh8ymHw/5puk=,tag:NB+tmVUhZ+eEUC+C9psDuA==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:Z0AKNJDTQI8GCCwjLcW7hgjBX9HTPDD6TIuMm5d2L72Dqj/YFtemqUonq5k=,iv:viOF5kTYw0upyc18iTFLog1KjaBIzveK24YEJxBVrtQ=,tag:lKx8jXpz7RTHWECmsFfV8w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:By1PjKjnMTqSBF9yfJIMfilEnFySaLwVuUY+V+KAi5o1Ob5apWvA3c6lym3CNEa027C0BsZZMOyy2T99mFopuVFJKiUx0BdB2bIBqBB6n4MZ8R0CJoGbLGfySvtt6R1HWw==,iv:iQFOAu8KTG5dB74huJ32+YbvG9jPP13pVNvkODlki+w=,tag:dTOuxBur4FD+mHwP3lrrIg==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:J/DViqVYOe8HcnRWwQsK+v04uRbmq9JSdljGxlfvs8IOM71KfIFr4rCqL14=,iv:oW5JgRdyrJ2htxRJ1+LPiHptjhcGzP2MaaFb+zWxp/Q=,tag:e+sIsQZm+z00/tUx8F/JOQ==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUXRjRDdoOTdkT3N1eVJ1
            WUFxbGp1bVJwekZQTEdUQTl1OVFpTFlXaTM4CjlxaXlDTExMM3VydTNXUmhjRjJE
            S1NnZEkybjdJS0hwdFord1pSQnF0K3MKLS0tIFJMZExSSEtScGlXWHZ1RHp3MTdU
            S0QwWDBMajVYM2hoa0tQeGJ2SFBGWUkKkXjLOVjY5e44stw9kAhfrqzD4w9I3nB5
            /zMPL2hi5ki0VpsJ6m86Df3t5USqZ0mHO5Mx89suvdcWAna8ezstRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T08:14:38Z"
    mac: ENC[AES256_GCM,data:oIbXeBpdl0GnarvqSxkJOVtcVYCkRiQu7lO6pyeOKkBDY8ddUC5EPnt/aUFuoFCIqOVE142Uagi1PMBATz/cH2X2oLy8tI+j/WQAxI6OjwIuD8Dbd/ppal4l6WowoJuiqV/BS4o19iJvlrE0MboTT5KWIfBAxVjvppPKyiJYOnQ=,iv:bnXVaqHNwbAoePbMmSDpPIZVCpzInlBcTgNvm4nKSAA=,tag:Xi+vj2A4Gaa80w42vt3PjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
