apiVersion: ENC[AES256_GCM,data:Xgs=,iv:dezMlfIj4e9yT1ynJcXxyNp63rX1nnA91i9NJ34Y/Bc=,tag:zu+/9b4qoDpfTmyXOgOaag==,type:str]
kind: ENC[AES256_GCM,data:wE6qKXO5,iv:9QFRVZfFC16rVdMYbJ/I/anfy2ms4AiSxt7fopYQt04=,tag:2o+27D/qKlUKzDHaR/Vb3g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7nGIJ8r/0kma5Bsu4b/eiCSrBuhS,iv:/oltKGZNa1n/tNLOzK1/PAOYVD9Ohfi5AN7vFgHTDoE=,tag:zHhlYO+TR/JhuDIfmlYXDw==,type:str]
    namespace: ENC[AES256_GCM,data:UtQ4Mc2lqR7NoF1LCg==,iv:djWWBwt/wn9D5GFskjY13fvGLODqi8eZqduVWGttWPQ=,tag:4TjAxUnVlgW0jCpQNz0apQ==,type:str]
type: ENC[AES256_GCM,data:U2crfnRm,iv:w5/LCAQjwI+geufuHgGvhc/AvHUDhcH8vdO1QHbjs70=,tag:3UPTkyM0sQgYP5Jt6s9s/w==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:udCB88U8Kuz9YntUt8ZNSM0VSMIlbgkiLw==,iv:pN5foW/0CBZSp22PTnTcZTYJVN4WkyGfH2AhjuTvw5I=,tag:nZQr1V5fXMVnlKoFu6KYow==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iBN6xmTCOlR2YU7pxL7KB4ZU82iw9MX+mODrk6hxxA==,iv:iLldSQUkB0l4RlURkzLv/pIAX+upCyCzWW6bWcQJZaQ=,tag:+cT36LdPASP6u8bWmdyG+g==,type:str]
    FORGEJO_REPO: ENC[AES256_GCM,data:RlPaYWTr6LjwmONAHPjYztmGmpxiRqBLtF2yFEZvOa1iwGX3uSemHBvbVj7rh+0t/6fACiwpx9HFIqoISpXYGj+qkm666Yt1,iv:CKKUqBM4kWbCerk0oisCQSDT77AWHyGyFUlZPbg1AxY=,tag:tZKkZzvPCx0jj+v8FLiU/w==,type:str]
    FORGEJO_PASSWORD: ENC[AES256_GCM,data:p2X/MrWSRbmj5/ClDQDigVPH2CSvAzPgWn94qp2EmVmHGtsrK5Ts/R6cF9I=,iv:3ja1gJGWsSrFAL1iD1M2mAHcUNdKf9YPFaEzcWx6kak=,tag:C2KZKG2Pjgr6aBCWfXNQoA==,type:str]
    GRAFANA_REPO: ENC[AES256_GCM,data:Ilv1s5RskLYuQG9pV6vXbHg2ztT8zKFoWcLPxFuP0OnJdWEWfTRdmLi2q5q3Tc9s/kMU0uRTWQnvVtBqzGhfex1tmSuUPdJt,iv:fXcN5S2SMcI7BW+mEjrGRud4G7POodXXLuX/VGUlnHQ=,tag:IQSML7gvMs1uxAORHA/Smg==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:j66YC2U1fS7Gc1eTSjJeKle6L82uO7kXKE2LOa/CyXN8BNCSBzWnZX/miB8=,iv:y4BRwjbQVnw/zMy5o3+DxspwTtX+aGNizfB9BZzrnAM=,tag:xryaEDAvkD8neWPKmZxgGg==,type:str]
    VAULTWARDEN_REPO: ENC[AES256_GCM,data:7bhylz04Nxwy8apaEp1+bG18bEBHYt/FDYu3k3PIHos66AVtpZJhUGtGpwFFn+/YrcOGw0HFMeLbE85ipjQLgIOq4ugQVvsxYoYpKg==,iv:o1HzPue6MQE1TSkpu40HQAFjmOPk8IjKBNYDxNvv1s0=,tag:KEuAGxNbFQU7aA7sqT5M3w==,type:str]
    VAULTWARDEN_PASSWORD: ENC[AES256_GCM,data:260au+iLdu00W+T8GtiNtUZJFh6CxyEdEHXDF3s5v5RQQ92Fq8G9PSPTAN4=,iv:5YJ2yxfupc5GeYgjBsyXRDpl0MrEoepExHuak7mkVeE=,tag:1Pq1N7qz/Vlh56/96lB0Fg==,type:str]
    HOARDER_REPO: ENC[AES256_GCM,data:Z69HJQbcRVU1puKzA3b9SgSbwUJl1Ml5rIOYrzwciOKh2bsVgzE3POlU0b+h5MziCgv7aeegqG6+iW6Tk51Upa1rNQYP194P,iv:2+WULNbxsRZRNpbqAXSa2EpGk6HpQh3d57gBuYI+jpM=,tag:91Dv85AWGWqNAQN0RMmSjA==,type:str]
    HOARDER_PASSWORD: ENC[AES256_GCM,data:OmrVfup0UOS5NTHElYa5m57th3EHo+shpmj0IAzSN82U9ROKPSlCkxBYVns=,iv:c8fI6t2YkFfW8qpPU1DNUU+fPOSB/9UoO/9zl+s6Fvc=,tag:IFTNn6GkLchK6JhDG0GmzQ==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaGU3QUovV0VIeUxjd2VW
            NkZPK0F6NWY3Uk41SzdqRE0vaDFjbElDNEU4CkhGeC9EKy91LzVUM2M5VndGeVFK
            UWR1SlhrRFdldC8vSXZQQVlNbXVlZVUKLS0tIDN6TTJSQVJnMkZXc3BqVE9wdG85
            Qi80UUhHbHR0Uk1hQU9tWXMveVZFL00K5EiSbPks8FpkaJ+M5Zu8jum81A3tOk+L
            X8W3IwaObeSSmVQIkspuxBDnzYqn6h8CBu4oQBFcRvGvSLudBdPZNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T07:50:22Z"
    mac: ENC[AES256_GCM,data:kMDBkWt20Eqz85R6MZXYyzqbCKp8Mu6CoahsZlyQf7If9be8uUJGlVDj8o+PvVhBe3CcoshWvc16B3o82ubB49H+8JhE96SqOpn0ZihsrJnuMpMHPNmPPKNm3owKv+h8ZuZCcSVK8Mlft5om8Xrqy9YQZ4B1sZm1BlFMHp/3mxo=,iv:gGrqpQ/PzAwMn/lA53iUn9S3hsNRJm/MZxVoWs/ceSc=,tag:/0GfJROB7bp9BsaqlHNlCA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
