apiVersion: ENC[AES256_GCM,data:Mck=,iv:mIi4QBbWk0Q3MH9V9rPv7RGYY+x26UulqHu5Zf3VfEw=,tag:YBeS/fQc3asu2o/VVif1Dg==,type:str]
kind: ENC[AES256_GCM,data:wxUMtALX,iv:Fyup2xduN/7abw+mUXTQO+HyfsZMvfxhzP8LPZ4FowM=,tag:ByjZvftTpuAu6ZLQfgiMyA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vh2UsTM6lWP8vLQ4krGak6Wqv8lD,iv:VF+jZwzxj8ORpNp7xWTszqt4YJFbzTAHGtFH/tKDfhs=,tag:KYcomnlafcf8Kq36sqiRHA==,type:str]
    namespace: ENC[AES256_GCM,data:Zmn75YLumQ==,iv:tBSw+jdg7sIatjav90pfExyWwoTr8Tlb4xGI7pEgCSI=,tag:xNkuRa7UvLhX8UYKJ9Bkow==,type:str]
type: ENC[AES256_GCM,data:jnA4JoyI,iv:hSBemZw7xFlvhO4FCsuVCKaqvOPmEBRqv3XMGnuAG+w=,tag:ZFr/b4BA3Z2kAi7QabIehQ==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bx2kllJyquWj7GosPY3hfXM5h4dqKDzSSQ==,iv:cUNcxDZOMxnQyG8OdWgc3Q7o9jZXXzl9u6fnhaNfQXA=,tag:Zhxx84HKlPKBxs7wrQegaQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Rr9Bkq2LZCHIj79fxrIcYhtVmsVh9dKw4/sMf0W0PA==,iv:BJ7aYGWv4GkQs+B0//NuCBWGYTYnoAXghEu1XaxmnZk=,tag:vgZdboWHOIgI7SrGuApioQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:UiLZaTnd6pDD1J0TkteMjFv4QLSBwy+/qh/UGtCpYJykQhVLP4gmwfoR1/rLEAKI1q7v2sB9g2+BA/JpzmLksuAaXug=,iv:5pX+ixI804xvrFPJmTbIeyau3b08OsxMIKBqBS6pNyo=,tag:oIVB85IMU+L71CfoX/1+sg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:sm0uHBoLi0fD6B4KxloDxHpQFcoRXDCz9whMfi+h4ksRwrNkaAyu1+y54k4=,iv:dz/sNas0p6kuvSdnrDr8SGaRZL03fLWNhBB9pKgeHN4=,tag:IbzyKDwjKgBcQFrbN9oOOQ==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TzR0Ty9kQ3ZnMHRTZVJi
            cEFKVDI5NU9TK1NvekNkWFdaWkFURTdidWtNCnNnZG11OEloN2w1MkhsTm41ZFVF
            aFZmN25zNXlqbUw3b24ybndmQjVYUTAKLS0tIFVwbmZXYXQxTytLSWhxL2o1RVFB
            THcvRE41bzQzQWhBNGFJeEplbUlyMGMKtFigm52r6tZyv0xUyo+I1n/gsND3rsmf
            VDFqHmTUqeqWKhswg1YN4ylgYUcYX5BDKlxcChM6h0fw7jvA89li2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T23:58:44Z"
    mac: ENC[AES256_GCM,data:rMYgpYQGZ6wzL+js1QNND3ledBKSSZxguzE1YsdHkG/HDu+yl2OUrETg/OCq0cHoaFLOjRlqEe1fjbvf8pl/CA/PI8gTELXipqPYueljhOnwATY4gJH8NxVER/U+bnwrTaC4agf7qEL1mS7gBIw6SYP6G5kERQ8vuCK+uTN+nDE=,iv:/FBZpJsn3j24BUOwL6KHZcwL+ty5HL4bmWmMfMfPWS4=,tag:8qAjhS0SQIzqJa5ufxZy8g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
