apiVersion: ENC[AES256_GCM,data:psE=,iv:nEqxzMJgUkYT3l1LLR/hTQicZsjFi7s0kgPXwEPOS+Y=,tag:0PvW8gqgOxexbBl9GBCpJw==,type:str]
kind: ENC[AES256_GCM,data:BDk3ZQjo,iv:b5ErTBFpf4DqFmSwG6pDPHRQesmKersol54xr8gM25w=,tag:fXqLfOon69YdZLwS4RJYHg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mVgiz63ZRDuw0pHqIRomOYq4Pi4F,iv:E4AKfd75jNi3Bgf8wJvEX/cvcpyqFU1La9lt8qOgbBM=,tag:likxFj6POdV/VStRF7hHIg==,type:str]
    namespace: ENC[AES256_GCM,data:/X0R4nIHRw==,iv:Dql54dTTztXh7vYFjJPoFPxYDidTA7HaUakvx3eYWpg=,tag:pX0huPPKJCE0EOtaue5vdg==,type:str]
type: ENC[AES256_GCM,data:Xku0iJzg,iv:2jz5Ij8HPHDTF6xhd52X1FQ4HoT0o6O6gxMjVaXH4OE=,tag:PMzgbWffBjWumKH3Jc84Sw==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:chSK9LkVdrqy4hCAUDFgMQcQnVual/2h8w==,iv:1uuo3PfOFdEmyla0TuskqccrNV06Tni7zXzgTMKjKtw=,tag:uvnGiDByB47YWjEDB9TUMg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:chTYHPvnlqxic2jyTTk9PCtgueGxv8lC+PZJG6qjcw==,iv:dm5QydfD5o1V4Y7XwfeAjqcYOTKT2F7baoJ2yBjk54o=,tag:m9ZDNSQzPDRCYfXCVisLLw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:SI/qLnLJLpRZld+aHEhqIucnw6NjJ/fm0OKqgzIL4KyzQ0PjZSiA/s6XznKwKwFX979dUQ+o3nRyY528rbEb8Fmn00wLMfaT,iv:eD2mQF67X7jtAWcy5QhhJ1z8Ma+0o4SIhmRp8abOesU=,tag:8mWqsmr2DbjrcJzAxF0peQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:qjpmWdltUqhlVUTXPLwyBFWho8TYb70NrLMUAv1/ALz1i1g4vfF8YTpbe78=,iv:R51rI3R/RxVpUdD5/SSOP/od9gSELLFPso/W/SSXpzI=,tag:9nUkqBVSZ2MBZ6joHTkG5Q==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTWk5RVZBMkxYTElvR2Zz
            RzlZVi9TSlAyT3hhK3VCNUEwV3l4R0lLMjJFCjFEV2hUaXE2NDYzYjVHYjQ2S1Zy
            dWhPbE0yWTR2N3crS2xEWnJSVUJrUXMKLS0tIFplRUJ1THllK1V2STl3NEp3U2F5
            d3E3eEI3SHdua0RQZGNFU2ZPemlGU1UKdmSDhGrlKy4vgfXS6sYq1RuI68cNtPMN
            Hw/3QHDUlEyGKl/jsMhHkicPDYJR1gAxSiEJp5SnStTLzZp0FBNK+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T00:19:48Z"
    mac: ENC[AES256_GCM,data:oD/Z3pJR2TTHHWKWFCcpOI8wh8xpgCnfKRULvDJFVKM7VA+sZCkSZ4XXxh7YrVYWmVPE4N90bd7NBTXqvCT8m/HQZd0ksrR+jYwdoNmBpue1L41yz2RBsjBM2Q9X535dsH8g8XnMVojRpLh36Zd8dwAtrJE2EeDOcdqX4Oq7sYg=,iv:79MMhRaCv1+R5PqeMXuUSLmp/OYPfyhp6Lt/o++qEj4=,tag:9eQWM7iJfYup+4080Jmu3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
