apiVersion: ENC[AES256_GCM,data:548=,iv:8Fjc7Aj10Oeir1R5Ec1hD/wCxHq7w2LWdOTgcO/HdCk=,tag:fgbHDuabkrDKVbqwdr5e8w==,type:str]
kind: ENC[AES256_GCM,data:tZfD9W51,iv:nR6g8f45sU8H/Q+inXcKM9g1hp78n7hPoCAsVCaG/28=,tag:VGs7AOuMd/EMCGocaMleFw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1JMgT0W3S/ygJjThg8t1xU8=,iv:p3MN2NneVGLqFWG4VsVvO6Rqn0W2Sk9COss4nPKhoMA=,tag:JXLPnZYMDuUeE+TjrU9o+Q==,type:str]
    namespace: ENC[AES256_GCM,data:Zr6nW6DRzA==,iv:pbzBbIq330dJQ/1cj7w3Ymt5K6WK5YpUc6D1gO7KE84=,tag:e81fTByvudOdYBaM2vrO2A==,type:str]
type: ENC[AES256_GCM,data:OrsMJg8H,iv:CfhRnq7EK6VjTAOKoytWbkSFSnf0u1tK9xFmgJ4AbiY=,tag:EVmOvhN2/I1cbU9KWNMIOg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:bk6lZt4MdtldxYacrh6OwXbULq7J9nCUX9jUz2zAUCs=,iv:dBpdEBjH13CavTYpWX3pjwUv8zGQx2iRq0MSCUySpR8=,tag:y3pKTR5xHpEPn2G2EvKnoA==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNS85ZkFBK05mTXZCcHA2
            TE92bnZiSTZKcFRpUG1yZVgwYyt0amZuSlhJCi9SeUhaZXRQdGRqK3N6K05jL29P
            cTJjc0EvWWQ2RTNBNEV3OFd2dGhEb0UKLS0tIGhVVUZRcEkzRXhWeFR3eUVWOUlX
            cndlQUxEYzRUYUxXYy90TFlWUEtlSXcKZM+4kArpX43pSri/iU2y4MAT9kRhQO5T
            RY0TPhnk2jvIMKmv/vwQXP+3AzZwE2srWblLGQca6QTSV/K2iwUo/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T15:45:16Z"
    mac: ENC[AES256_GCM,data:pGviOl4d5cReL+FlMrEhX83fS/SUP+SS9q4dMj47GoELJVAdXmaAYr0liRuOu64tsgZ7uwcUxm0MVxXItR0dacg3zx38B0jJl5JZwvtraIZl64Zta3WpDWf1woIxdVuXGe+d6ctP4f5c/rNfyHgX6660toBPyd0bdiXQfz5QULg=,iv:zs3TuhGtESqtZ+GoknUGepEFWJC6lhWqXeQ7QnNxsEs=,tag:KRleBYyg7OBbYPNgHJGKmg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
