apiVersion: ENC[AES256_GCM,data:mlM=,iv:rDkbfUlt/9Jn+u+HYf4lN/rqlYLJGV3igINEPLR/TxM=,tag:EFMBnN7HxJmEcJqwvTyrNg==,type:str]
kind: ENC[AES256_GCM,data:XZ8Zza8q,iv:Tj8EYNMXRZk7ay+N8D6uXVIPBSXqrdTDvI/GUNC/Y1o=,tag:ujE6Sf0NtafXJqv4t8UASQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wpTsMeI7xu0iuIalNWTcGyE=,iv:Qe/vzqFNKQHwOqyN9Ix3b5TdxY3YvpHWvhRsRnQ+iUg=,tag:tT5Qos/OH3UM409Yh8h4FA==,type:str]
    namespace: ENC[AES256_GCM,data:MbGhn0pzEw==,iv:2VPNAKhp3SL7+xFZp+nhzvqJeaD4qC5omGBUV5XeS+I=,tag:PcNZ8D/UMmhzSHkfjosRhA==,type:str]
type: ENC[AES256_GCM,data:wBt79+EN,iv:WgyibS6q/32d6WrSybv7v0BcEbe19ld5lnlOsYUKZks=,tag:FK3No69TskP4pARqyeAQZg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:2ljXgzolo6D+7nQpGQ9/Wxn2M+CcTplE9FGs8urejXA=,iv:/+BkVsKIsYg++1/B+eofzP1Qs21iU4dU2abVMooRbV4=,tag:YWs65Ouak0PFkR10BJtBcw==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ2R5YytpSG55ZncrSnVX
            VXNTMkUvQ2Y1amY2aHc1TytPN2xsYkRickNVCjdwVWtQRWorclpPR2RqdzUyU0Q5
            TGliRWRxa2t3cDFDUUlraGNjcW9WVEUKLS0tIDhDc1pMUngzM2QyTzc3Q2RXVURo
            bmFpampqSlVVSVdyS3FkTFZCTk03MVEK+W14QZ1JS8QUjEF2x8kC8igjc8exqTw6
            T7P4Tiw2kImBwb6fclDz2NHkiCk1YKzsqRbFbnFtUVwMwdt181JZ5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T12:56:39Z"
    mac: ENC[AES256_GCM,data:Ul2B0Uv0kszqULu+le9r+qPUVVD8V+meag604MXtzimuNE7FY5ZXg+M7+RzGEhENzXUp9dDIDvjBP/xY/gictxwgmaeJxfGaPqaKgvEWTEsTaCeG3GitmPrDGH2A8H9KOChp4wlusmkZocUwGMA/4vFydatCSRmLukBA82+CVxs=,iv:3LIAnM4eV//Sadv2sncAhmFoERqeRZ1smdHIG+TAO/U=,tag:WRH2xaFOF5QvpUOYJ7xcAg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
