apiVersion: ENC[AES256_GCM,data:7nQ=,iv:J8xjLwppAwqTglJ9ZvViGp+bPnhQ3rTRf/nPzfaARdg=,tag:EwM28rTQYrTrov81OFygHQ==,type:str]
kind: ENC[AES256_GCM,data:N7IT8hBa,iv:ZccaDV3CPuL2WNjq4G+ieO4jVqPGakMOV2Z8edd9uc8=,tag:/cFQdNTWC8BgVGFAbJkjWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1krrFnK+KFFcFHgEVQtq4L0=,iv:32skCQg8l7cdRSTgnIKVKspKUUxTevio/wfnGg7bNCU=,tag:6hMcWn/iMAaZknduGPUNdQ==,type:str]
    namespace: ENC[AES256_GCM,data:L1aeIrOZlw==,iv:yOgns7GWJHS2wSV2ycpjVUJBEPjfRWg+DpLJIhWIpHQ=,tag:CM8UShQOSVsDczLsQew8Rg==,type:str]
type: ENC[AES256_GCM,data:AYcujgF8,iv:JD/n/A19uKrngTHIK6p0P5Zc/ybhPuYj1cHWjK22zm8=,tag:gXJ2ljXIE988QfhSC1/eew==,type:str]
stringData:
    password: ENC[AES256_GCM,data:8ujAiSAu/6jWz/bMtzcu0tQTlmbpkjHuDB8udp2ptNc7ay6wG4L2TDqopcLI+yZpvTOjngIZDddZilsJG5vWrw==,iv:sQQktWI0dmHzchgQ9dkRhKsZMdMup52ezCxN5ykBCtc=,tag:xXVzpgzwoGuuSwX++kr0Ww==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUDlQelZzQkJvNEVWUVp2
            eGFFZ0N3U1ZHbnR1QktlaFp6ZzhpQi9JZVJRClJUa2xyLy8vVCs0WWw4YlVyVkEz
            VkJ3UXowdCtST01JODc1NXRQai9pWlUKLS0tIG1hbVU1Sm5WektMMHVVVHRiVVhr
            aVNRQmtpTTZjL1piVzdLWHh5Z3hHcG8KnL+mzHfx2B0GeLmUeGomqghppSrixPbp
            yeLEDuTM5JNq7KWO4BKYbz4jBduDesKwtuJ9h8M3g6iZJD30jZmUKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T11:39:18Z"
    mac: ENC[AES256_GCM,data:Fc+Kq9JlXl1EXLZ1xk1Fakvv9sm/vxO5tDYEtn41+3IShlWY0r9RXVMCKJYvc7ITtcdFLgRfkpvbVfSyaqJMcO9rB5Jo+OQ3Nx1StjdoGUHPlwyNVqWgvw6qjetM5wWGVSVKTv7k4khLebLf+Png6zHPk9GsJFdKcsuqbhwJnf4=,iv:diyusxiNRl555VY/MbLIVnO2uT0y1D1oQ3463btKkpU=,tag:CvJummzPI1ZgCtiQfcFc0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
