apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: forgejo
  namespace: forgejo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`forgejo.pedrocoutinho.eu`)
      kind: Rule
      services:
        - name: forgejo-http
          port: 3000
  tls:
    store:
      name: default
