apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: forgejo-backup
  namespace: forgejo
spec:
  sourcePVC: gitea-shared-storage
  trigger:
    schedule: "0 2 * * *"
  restic:
    pruneIntervalDays: 7
    repository: forgejo-backup-secret
    retain:
      daily: 7
      weekly: 4
      monthly: 3
    copyMethod: Direct
    cacheCapacity: 1Gi
    cacheStorageClassName: longhorn
