apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repositories.yaml
  - cilium
  - longhorn
  - snapshot-controller
  - cloudnative-pg
  - traefik
  - cert-manager
  - postgres
  - volsync
  - loki
  - alloy
  - backup-verify
  - nfs-provisioner
  - coredns-patch.yaml
