apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack
  - forgejo
  - headscale
  - tailscale
  - authelia
  - monitoring-ingress
  - longhorn-ingress
  - hubble-ingress
  - headplane
