apiVersion: ENC[AES256_GCM,data:S4k=,iv:phx7PgcRRdjXva/YtwzLj7J07ix+f6iDb/WKT4YjQP8=,tag:gZl9jgojxHlSv0pxe+XFlQ==,type:str]
kind: ENC[AES256_GCM,data:eDHAOS7I,iv:fHaZYgCKSNmvGDAyHF0LlbzBvGIGE2crzSO1QAecR7A=,tag:wMqqvuIc4PdqYwrStIs81w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aTAvyUpsTSmdFe6+ly+8CQ==,iv:BF7P/+Rvu5S4L7dgvkVvAeEfJp5kmbGafr5hmT5a3yA=,tag:EVoVnV2reXv5PGSKbDTu+g==,type:str]
    namespace: ENC[AES256_GCM,data:tloNL2NOyX6cJ/URDuw=,iv:Yrxni2bURpswNIxUQrxQcldTXQYI825UNKAcc9okgi0=,tag:xF/EIpdxyYwmvrvxkwnC0Q==,type:str]
type: ENC[AES256_GCM,data:SrVfG7WW,iv:1hrPdgSSxkreC1MSrE4xWjOHnuNANZAu1cuzhnr9+jA=,tag:txv4vvEKaDo7MgDsaSr63w==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cTxkhlpNeQ2k3xsHlE2yWKD6RDMxbDlnjw==,iv:1U98OX7MXeG8oRebiFbEcGr82/ECK8nlI3mv2L5TmWc=,tag:2WH9OdOZi5Hl8giPFlvBfA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:K9/F4kc+UInIsyjDdx0L9Bx+3E2p8Wf8ntAqpg0h4w==,iv:5Fy/3ORyZUcoT/h3dPUQzbNnNTbkymUGIY6FU2po63I=,tag:8qiyix4c7qlqU/syowuH7A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:OJQS6HwFNUTJ3KjI8Ei3nKXjS+DccLV6QRcg0BLButIU48S0m/cWhX1dhwA=,iv:CdJ5V8Ytdh9PHSe20fiPHPv9JxDsfC+Bh+zVdY0Gygk=,tag:Ys+7bWEHip/hcSMtELpYzw==,type:str]
sops:
    age:
        - recipient: age1js6ffj7uq2d5ysqcxwlwnrrrwehnpe8jd6yfyhz55wp8tav66f2qyl22ge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a3NJR1F3a0RmOG1Jc1c0
            Sks1NlliWWhIZDFpNDE0R3NHRUh1Q25QL2c0Ck9xNTJ4VGlwS25xWXMrZS9xM01x
            Q0lmWEx4SU0yU3JJOTUwUW40V2x4MHMKLS0tIHJsb0ExMEE5ZkY5T0EveGN4cTZI
            QzNuSmJvTk0wbWd3S20xNlNoVjZtbWsKnEmRnxOAxrzybyCCxBx43GcPWq4aQaR1
            +p+hhqKdD26XJIS7ifdcoHzx07Z2yzPJQpCrlIHfmnPAP5yW2mRtVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T23:50:50Z"
    mac: ENC[AES256_GCM,data:ZlLxC2iHEHl8kE5Z/eOI9kLUtvaYxe6ApOVH/hO2hPnC0IcKmTbqJFFZxIgTIwvZPNk7um+/HRlFxr4PkNuH0JA8YWamfXkMLL5KM7uqn692IWZvtpchWWtfffvYP57NdbS5nilDLc+2AaN3jblwMFZMfRaj1p9LGGoISyncsOk=,iv:KLZM2QRRrYYy4yxQYPkLkNMWUWfaYQiaaq0J1Zftkx0=,tag:5uVSKVe2NgtBzZxl3pP62g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
